#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run function temple_boss:set_variant/attack
execute if score .this aj.frame matches 10 run function temple_boss:animations/animation.model.attack_1/zzz/execute/39
execute if score .this aj.frame matches 18 run function temple_boss:animations/animation.model.attack_1/zzz/execute/40
execute if score .this aj.frame matches 26 run function temple_boss:animations/animation.model.attack_1/zzz/execute/41
execute if score .this aj.frame matches 40 run function temple_boss:animations/animation.model.attack_1/zzz/execute/42