#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-22.6063f,0f,0f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-21.7593f,0f,0f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-20.9122f,0f,0f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-20.2606f,0f,0f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-20f,0f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-20.1749f,0f,0f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-20.5831f,0f,0f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-21.0496f,0f,0f]