#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function temple_boss:animations/animation.model.attack_6/tree/bone2_root_64-71
execute if score .this aj.frame matches 72 run tp @s ^0 ^-0.063 ^0.625 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^0 ^-0.063 ^0.625 ~ ~