#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.114 ^3.223 ^0.688 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.087 ^3.163 ^0.688 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.053 ^3.097 ^0.688 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.021 ^3.054 ^0.688 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0 ^3.062 ^0.688 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.008 ^3.135 ^0.688 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.009 ^3.254 ^0.688 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.006 ^3.398 ^0.688 ~ ~