#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.234 ^2.595 ^0.407 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.303 ^3.218 ^0.398 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.09 ^2.779 ^0.391 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.253 ^3.028 ^0.387 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.081 ^3.214 ^0.385 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.214 ^2.776 ^0.384 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.363 ^2.588 ^0.384 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.191 ^3.212 ^0.385 ~ ~