#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [29.537f,-53.3333f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [29.5142f,-52.7344f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [29.4495f,-51.0417f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [29.349f,-48.4115f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [29.2188f,-45f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [29.0646f,-40.9635f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [28.8925f,-36.4583f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [28.7085f,-31.6406f,0f]