#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0 ^3.024 ^0.385 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.187 ^3.212 ^0.392 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.321 ^3.032 ^0.404 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.203 ^3.155 ^0.426 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.088 ^3.224 ^0.448 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.283 ^3.03 ^0.467 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.438 ^2.789 ^0.482 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.149 ^2.63 ^0.49 ~ ~