#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.007 ^0.863 ^0.644 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.008 ^1.017 ^0.647 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.009 ^1.176 ^0.65 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.011 ^1.337 ^0.653 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.012 ^1.5 ^0.656 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.013 ^1.662 ^0.66 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.013 ^1.823 ^0.663 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.014 ^1.982 ^0.666 ~ ~