#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-171.8519f,33.3333f,180f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-170.4932f,68.9063f,180f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [10.9013f,74.5833f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [12.3197f,37.4479f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [13.75f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [15.1803f,-37.4479f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [16.5987f,-74.5833f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-162.0068f,-68.9062f,180f]