#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.375 ^2.625 ^0.688 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.117 ^2.953 ^0.688 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.187 ^3.25 ^0.688 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.117 ^3.054 ^0.688 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0 ^2.812 ^0.688 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.187 ^3.062 ^0.688 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.125 ^3.25 ^0.688 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.187 ^2.812 ^0.688 ~ ~