#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-160.6481f,-33.3333f,180f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-159.3372f,0.9896f,-180f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-158.0859f,33.75f,180f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-156.9063f,64.6354f,180f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [24.1898f,86.6667f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [25.1904f,60.4687f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [26.0836f,37.0833f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [26.8575f,16.8229f,0f]