#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [62.2222f,-26.6667f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [61.8077f,-21.6927f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [61.4063f,-16.875f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [61.0308f,-12.3698f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [60.6944f,-8.3333f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [60.4102f,-4.9219f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [60.191f,-2.2917f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [60.0499f,-0.599f,0f]