#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^0.281 ^0.203 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.121 ^0.358 ^0.226 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.249 ^0.452 ^0.299 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.353 ^0.56 ^0.429 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.398 ^0.681 ^0.609 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.353 ^0.813 ^0.804 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.21 ^0.955 ^0.959 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.001 ^1.105 ^1.018 ~ ~