#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.282 ^3.128 ^0.503 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.264 ^3.752 ^0.494 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.061 ^3.314 ^0.487 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.233 ^3.563 ^0.481 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.094 ^3.75 ^0.477 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.206 ^3.312 ^0.474 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.366 ^3.125 ^0.473 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.19 ^3.749 ^0.472 ~ ~