#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.142 ^2.6 ^0.906 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.018 ^2.756 ^0.945 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.159 ^2.904 ^0.894 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.241 ^3.043 ^0.786 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.254 ^3.172 ^0.666 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.214 ^3.29 ^0.566 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.144 ^3.395 ^0.503 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.068 ^3.486 ^0.474 ~ ~