#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.21 ^1.263 ^0.952 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.343 ^1.426 ^0.776 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.346 ^1.593 ^0.557 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.217 ^1.763 ^0.384 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.012 ^1.934 ^0.328 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.18 ^2.104 ^0.408 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.282 ^2.273 ^0.581 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.262 ^2.439 ^0.772 ~ ~