#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [76.3278f,28.0247f,17.2494f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [72.781f,15.5986f,16.4742f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [69.961f,5.2983f,16.4929f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [67.6056f,-3.0006f,16.9098f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [65.6468f,-9.4447f,17.4968f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [64.093f,-14.1897f,18.0951f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [62.9741f,-17.3924f,18.5894f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [62.3104f,-19.2067f,18.9052f]