#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [69.5971f,3.9868f,16.5347f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [70.8313f,8.4626f,16.4285f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [72.0166f,12.8039f,16.4243f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [73.1297f,16.8672f,16.5109f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [74.1423f,20.509f,16.6668f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [75.0176f,23.5867f,16.8605f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [75.7096f,25.9588f,17.0514f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [76.1647f,27.4849f,17.1947f]