#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.05 ^2.674 ^-0.096 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.299 ^3.001 ^-0.101 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.581 ^3.297 ^-0.113 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.473 ^3.101 ^-0.13 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.307 ^2.857 ^-0.15 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.435 ^3.104 ^-0.169 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.054 ^3.289 ^-0.186 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.293 ^2.849 ^-0.198 ~ ~