#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-41.5373f,4.5575f,-37.2625f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-42.282f,6.411f,-35.2592f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-41.5373f,4.5575f,-37.2625f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-17.9034f,-41.766f,-54.5881f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-16.6606f,-44.2437f,-54.6536f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-16.0117f,-45.568f,-54.6554f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-15.8227f,-45.9585f,-54.6513f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-15.9739f,-45.6461f,-54.6548f]