#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.117 ^0.614 ^1.494 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.598 ^0.786 ^1.276 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.863 ^0.964 ^0.803 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.787 ^1.144 ^0.256 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.387 ^1.327 ^-0.135 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.174 ^1.509 ^-0.2 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.658 ^1.69 ^0.089 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.87 ^1.868 ^0.605 ~ ~