#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [-82.2867f,-35.7709f,97.8275f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [-81.9662f,-35.7724f,97.3383f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [-84.255f,-35.8051f,100.803f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [-90.6579f,-36.3334f,110.1381f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [-114.2612f,-40.6711f,140.8177f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [-166.2405f,-47.6637f,-161.7309f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [124.8304f,-42.0869f,-90.1216f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [74.3198f,-29.1149f,-34.4752f]