#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.489 ^2.615 ^0.152 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.462 ^2.562 ^0.143 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.428 ^2.504 ^0.135 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.396 ^2.467 ^0.128 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.375 ^2.478 ^0.125 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.367 ^2.55 ^0.127 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.366 ^2.664 ^0.131 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.369 ^2.804 ^0.136 ~ ~