#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.219 ^-1.063 ^-0.094 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.002 ^-0.982 ^-0.136 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.273 ^-0.884 ^-0.097 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.551 ^-0.771 ^0.066 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.759 ^-0.644 ^0.369 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.807 ^-0.504 ^0.777 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.629 ^-0.354 ^1.192 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.227 ^-0.193 ^1.469 ~ ~