#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.391 ^2.109 ^-0.156 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.64 ^2.436 ^-0.164 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.919 ^2.732 ^-0.185 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.807 ^2.535 ^-0.217 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.634 ^2.29 ^-0.256 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.753 ^2.537 ^-0.297 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.36 ^2.721 ^-0.337 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.584 ^2.28 ^-0.373 ~ ~