#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.073 ^2.089 ^-0.402 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.393 ^2.71 ^-0.422 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.112 ^2.269 ^-0.434 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.21 ^2.516 ^-0.438 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.182 ^2.7 ^-0.435 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.064 ^2.26 ^-0.428 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.55 ^2.071 ^-0.42 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.02 ^2.695 ^-0.414 ~ ~