#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [76.3278f,28.0247f,17.2494f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [63.9244f,24.7623f,33.5139f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [76.3278f,28.0247f,17.2494f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-90.6579f,-36.3334f,110.1381f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-84.6874f,-37.058f,101.6805f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-81.9935f,-37.6188f,97.635f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-81.2639f,-37.8091f,96.5079f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-81.8453f,-37.6559f,97.4073f]