#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-41.5373f,4.5575f,-37.2625f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-33.6951f,-6.1059f,-37.3179f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-26.9791f,-14.8826f,-38.538f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-21.1519f,-21.8323f,-40.3948f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-16.206f,-27.101f,-42.4739f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-12.2403f,-30.8784f,-44.4257f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-9.3708f,-33.3651f,-45.9751f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-7.6659f,-34.747f,-46.9443f]