#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.724 ^1.431 ^1.392 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.187 ^1.603 ^1.701 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.409 ^1.768 ^1.661 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.87 ^1.923 ^1.326 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^1.087 ^2.068 ^0.836 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^1.053 ^2.201 ^0.342 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.835 ^2.319 ^-0.05 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.529 ^2.422 ^-0.297 ~ ~