#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function temple_boss:animations/animation.model.attack_6/tree/left_leg_display_64-71
execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]