#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.742 ^2.041 ^1.135 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.347 ^2.209 ^1.485 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.15 ^2.369 ^1.555 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.583 ^2.519 ^1.363 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.841 ^2.659 ^1.007 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.899 ^2.787 ^0.609 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.794 ^2.901 ^0.264 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.597 ^3 ^0.019 ~ ~