#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function temple_boss:animations/animation.model.attack_6/tree/lower_left_leg_display_64-71
execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]