#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [54.4226f,-25.3869f,-8.2733f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [54.2947f,-24.8165f,-8.234f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [53.9377f,-23.204f,-8.1294f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [53.3948f,-20.6977f,-7.9844f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [52.7091f,-17.4458f,-7.8254f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [51.9193f,-13.5968f,-7.6764f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [51.0583f,-9.2995f,-7.5559f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [50.1537f,-4.7032f,-7.4768f]