#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [49.2286f,0.0427f,-7.4465f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [48.304f,4.7886f,-7.4673f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [47.4008f,9.3848f,-7.5371f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [46.5423f,13.682f,-7.6484f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [45.7555f,17.5309f,-7.7889f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [45.0729f,20.7826f,-7.9402f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [44.533f,23.2888f,-8.0791f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [44.1782f,24.9012f,-8.1795f]