#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [46.4499f,-28.4645f,-7.2391f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [49.7497f,-42.6148f,-8.837f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [53.6279f,-54.2857f,-11.3579f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [58.5446f,-63.612f,-15.1977f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [65.0687f,-70.7191f,-20.8876f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [73.5836f,-75.7379f,-28.7861f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [83.34f,-78.8632f,-38.124f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [91.5042f,-80.4379f,-46.05f]