#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.155 ^1.183 ^1.575 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.38 ^1.356 ^1.526 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.784 ^1.521 ^1.206 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.953 ^1.677 ^0.747 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.877 ^1.822 ^0.294 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.625 ^1.955 ^-0.046 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.29 ^2.073 ^-0.231 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.042 ^2.176 ^-0.274 ~ ~