#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.51 ^2.212 ^0.341 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.508 ^2.35 ^0.342 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.507 ^2.975 ^0.341 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.505 ^2.975 ^0.323 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.496 ^1.727 ^0.262 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.479 ^-0.07 ^0.174 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.454 ^-1.369 ^0.084 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.43 ^-1.34 ^0.019 ~ ~