#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-164.1861f,41.948f,-176.1314f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-149.4371f,78.6245f,-164.5579f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [11.4537f,62.8202f,-6.9495f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [18.3852f,24.3181f,-3.6757f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [23.0882f,-14.5579f,-3.6698f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [29.5025f,-53.362f,-6.3325f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [144.7497f,-85.4522f,-118.0466f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-156.259f,-49.7143f,-173.3958f]