#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function temple_boss:animations/animation.model.attack_6/tree/lower_right_leg_display_64-71
execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [0f,0f,-2.5f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [0f,0f,-2.5f]