#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.412 ^-1.276 ^0.057 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.227 ^-1.194 ^-0.044 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.025 ^-1.094 ^-0.086 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.316 ^-0.979 ^-0.02 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.582 ^-0.85 ^0.191 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.732 ^-0.708 ^0.536 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.684 ^-0.555 ^0.943 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.405 ^-0.393 ^1.284 ~ ~