#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [54.2576f,-55.766f,-11.8167f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [52.2614f,-50.7076f,-10.405f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [50.6577f,-45.7874f,-9.3733f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [49.3632f,-41.1735f,-8.6203f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [48.3273f,-37.0318f,-8.0761f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [47.5224f,-33.5269f,-7.6926f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [46.9377f,-30.8224f,-7.437f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [46.5756f,-29.0809f,-7.2887f]