#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [44.0511f,25.4717f,-8.2172f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [47.7736f,27.4515f,-6.0158f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [44.0511f,25.4717f,-8.2172f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-16.4925f,-25.3274f,-17.2459f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-19.8099f,-27.8399f,-16.0593f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-21.6332f,-29.1587f,-15.345f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-22.178f,-29.5441f,-15.1233f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-21.7418f,-29.2359f,-15.3011f]