#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [-17.9906f,-27.2961f,-17.6104f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [-18.0541f,-27.3786f,-17.6232f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [-17.6116f,-26.8019f,-17.5292f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [-16.4925f,-25.3274f,-17.2459f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [-13.3784f,-21.1402f,-16.1024f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [-9.0312f,-15.2698f,-13.6065f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [-4.3994f,-9.3311f,-9.8125f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [-0.2828f,-4.611f,-5.5311f]