#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-20.6624f,-28.4621f,-15.7307f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-19.282f,-27.4498f,-16.258f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-17.9263f,-26.4309f,-16.7514f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-16.8995f,-25.6433f,-17.1084f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-16.4925f,-25.3274f,-17.2459f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-16.6772f,-25.5723f,-17.2972f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-17.111f,-26.145f,-17.4106f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-17.6116f,-26.8019f,-17.5292f]