#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.318 ^2.089 ^-0.205 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.8 ^2.71 ^-0.26 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.53 ^2.269 ^-0.307 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.638 ^2.516 ^-0.344 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.251 ^2.7 ^-0.372 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.5 ^2.26 ^-0.391 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.112 ^2.071 ^-0.403 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.418 ^2.695 ^-0.41 ~ ~