#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.219 ^2.507 ^-0.412 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.589 ^2.701 ^-0.329 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.858 ^2.525 ^-0.222 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.833 ^2.653 ^-0.105 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.779 ^2.725 ^0.001 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-1.012 ^2.534 ^0.086 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-1.19 ^2.294 ^0.148 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.912 ^2.136 ^0.184 ~ ~