#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.115 ^2.041 ^1.547 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.403 ^2.209 ^1.472 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.774 ^2.369 ^1.138 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.904 ^2.519 ^0.685 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.798 ^2.659 ^0.259 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.529 ^2.787 ^-0.043 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.196 ^2.901 ^-0.188 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.121 ^3 ^-0.198 ~ ~