#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.498 ^2.674 ^0.505 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.754 ^3.001 ^0.496 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-1.052 ^3.297 ^0.471 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.971 ^3.101 ^0.431 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.837 ^2.857 ^0.381 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-1.001 ^3.104 ^0.322 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.658 ^3.289 ^0.259 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.931 ^2.849 ^0.195 ~ ~