#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.653 ^2.109 ^0.195 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.905 ^2.436 ^0.185 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-1.194 ^2.732 ^0.155 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-1.098 ^2.535 ^0.11 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.943 ^2.29 ^0.053 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-1.083 ^2.537 ^-0.01 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.712 ^2.721 ^-0.077 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.956 ^2.28 ^-0.143 ~ ~