#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-4.9432f,58.169f,28.5903f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-2.9115f,55.7521f,29.2162f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-1.0955f,53.3263f,29.6081f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [0.1807f,51.4577f,29.7754f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [0.6657f,50.7101f,29.8133f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [0.1824f,51.2256f,29.8823f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-0.9657f,52.4301f,30.019f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-2.3156f,53.8089f,30.1307f]