#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.219 ^-1.063 ^-0.094 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.42 ^-0.982 ^-0.009 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.622 ^-0.884 ^0.167 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.766 ^-0.771 ^0.447 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.785 ^-0.644 ^0.806 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.62 ^-0.504 ^1.173 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.265 ^-0.354 ^1.435 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.21 ^-0.193 ^1.477 ~ ~