#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [21.1365f,6.1942f,63.8042f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [20.0332f,5.5973f,63.3859f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [18.9416f,5.005f,62.9648f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [18.1099f,4.5526f,62.639f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [17.7792f,4.3724f,62.5082f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [18.002f,4.446f,62.7254f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [18.5271f,4.6192f,63.2316f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [19.1357f,4.8193f,63.8093f]