#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-120.9816f,46.316f,-159.1792f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-60.5529f,72.7888f,-102.6586f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [16.0227f,50.6029f,-31.6131f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [34.0108f,14.341f,-22.8803f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [48.9936f,-21.9876f,-26.9273f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [79.9882f,-53.0514f,-50.1749f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [150.2465f,-57.13f,-112.5584f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-170.6712f,-30.4994f,-141.3573f]