#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.358 ^1.431 ^1.633 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.25 ^1.603 ^1.693 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.773 ^1.768 ^1.418 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^1.058 ^1.923 ^0.931 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^1.062 ^2.068 ^0.4 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.837 ^2.201 ^-0.038 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.486 ^2.319 ^-0.313 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.111 ^2.422 ^-0.423 ~ ~