#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [149.7072f,30.5335f,135.6025f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [107.855f,50.9302f,107.7089f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [48.5586f,47.2398f,61.6986f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [11.7643f,22.2885f,39.9985f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-12.7637f,-8.3196f,36.6985f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-41.2147f,-37.5133f,47.7898f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-92.854f,-54.1973f,85.7594f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-148.6281f,-42.2615f,128.5256f]