#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.323 ^2.659 ^0.132 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.835 ^3.282 ^0.074 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.594 ^2.841 ^0.021 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.727 ^3.089 ^-0.023 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.363 ^3.274 ^-0.06 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.631 ^2.835 ^-0.087 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.032 ^2.646 ^-0.107 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.571 ^3.27 ^-0.119 ~ ~