#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [11.7606f,7.4524f,-86.7185f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [17.0826f,-2.8301f,-64.705f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [11.7606f,7.4524f,-86.7185f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-179.8086f,-15.285f,-136.6301f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [177.354f,-19.2974f,-140.6737f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [175.7339f,-20.9058f,-142.5282f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [175.2467f,-21.3093f,-143.0335f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [175.6368f,-20.989f,-142.6307f]