#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function temple_boss:animations/animation.model.attack_6/tree/spear_root_64-71
execute if score .this aj.frame matches 72 run tp @s ^1.023 ^-1.153 ^0.692 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^1.023 ^-1.153 ^0.692 ~ ~