#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [56.9635f,-0.6173f,-77.1267f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [56.4695f,-0.4596f,-77.1797f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [55.072f,-0.0199f,-77.3391f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [52.8963f,0.6451f,-77.6143f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [50.066f,1.4723f,-78.0191f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [46.7036f,2.3954f,-78.564f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [42.9322f,3.3483f,-79.2501f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [38.8767f,4.2701f,-80.0659f]