#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.203 ^2.282 ^0.45 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.737 ^2.897 ^0.406 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.519 ^2.45 ^0.367 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.675 ^2.692 ^0.333 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.332 ^2.871 ^0.305 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.618 ^2.427 ^0.283 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.034 ^2.235 ^0.268 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.582 ^2.857 ^0.258 ~ ~