#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [34.6652f,5.1091f,-80.9862f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [30.4302f,5.8275f,-81.9732f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [26.3079f,6.4033f,-82.9804f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [22.4377f,6.8319f,-83.9566f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [18.96f,7.1243f,-84.8503f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [16.0151f,7.3035f,-85.6138f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [13.7422f,7.3991f,-86.2044f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [12.2786f,7.4412f,-86.5843f]