#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.289 ^2.335 ^0.726 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.546 ^2.662 ^0.719 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.849 ^2.956 ^0.701 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.775 ^2.755 ^0.671 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.651 ^2.506 ^0.634 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.827 ^2.748 ^0.591 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.499 ^2.926 ^0.545 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.791 ^2.479 ^0.497 ~ ~