#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.39 ^2.668 ^0.255 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.611 ^2.878 ^0.347 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.758 ^2.717 ^0.437 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.639 ^2.856 ^0.525 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.517 ^2.937 ^0.599 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.702 ^2.752 ^0.656 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.849 ^2.517 ^0.696 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.554 ^2.361 ^0.719 ~ ~