#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.717 ^-0.757 ^0.189 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.8 ^-0.683 ^0.416 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.809 ^-0.593 ^0.701 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.701 ^-0.489 ^1.003 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.459 ^-0.371 ^1.256 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.11 ^-0.242 ^1.381 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.269 ^-0.101 ^1.32 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.569 ^0.049 ^1.068 ~ ~