#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.159 ^2.198 ^-0.013 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.091 ^2.526 ^-0.015 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.374 ^2.823 ^-0.022 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.27 ^2.626 ^-0.03 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.108 ^2.383 ^-0.039 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.242 ^2.632 ^-0.046 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.131 ^2.817 ^-0.048 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.117 ^2.378 ^-0.046 ~ ~