#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [-3.3575f,54.8444f,30.1807f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [-3.5338f,55.017f,30.186f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [-2.3156f,53.8089f,30.1307f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [0.6657f,50.7101f,29.8133f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [8.4332f,41.849f,27.7985f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [18.6103f,29.3089f,22.7778f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [29.1886f,16.4889f,15.1373f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [38.6023f,6.178f,6.6099f]