#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-150.6662f,0.9235f,-145.1215f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-128.9845f,29.4712f,-136.2496f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-92.6205f,48.1691f,-109.488f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-45.4376f,46.5556f,-71.4193f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-14.5358f,29.7673f,-50.6628f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [4.3174f,9.7914f,-44.2488f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [19.414f,-8.5091f,-45.1186f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [34.2047f,-23.2283f,-50.7028f]