#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [82.0753f,42.1215f,60.3308f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [68.6103f,34.7962f,53.3892f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [58.8693f,28.1298f,49.5507f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [51.6196f,22.5294f,47.4578f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [46.2175f,18.0957f,46.3524f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [42.3132f,14.8022f,45.7991f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [39.6953f,12.5705f,45.5431f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [38.2145f,11.3043f,45.4386f]