#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.687 ^0.208 ^0.695 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.579 ^0.375 ^0.323 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.284 ^0.549 ^0.082 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.087 ^0.727 ^0.056 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.395 ^0.909 ^0.241 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.536 ^1.094 ^0.557 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.477 ^1.28 ^0.88 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.262 ^1.464 ^1.104 ~ ~