#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [37.7466f,10.904f,45.4117f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [38.177f,11.2722f,45.4364f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [39.3951f,12.3139f,45.5195f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [41.294f,13.9348f,45.6885f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [43.7726f,16.0395f,45.9818f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [46.7368f,18.5291f,46.4415f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [50.0998f,21.3005f,47.107f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [53.7796f,24.2461f,48.0094f]