#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.088 ^2.372 ^0.388 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.45 ^2.991 ^0.364 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.237 ^2.548 ^0.343 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.399 ^2.793 ^0.325 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.062 ^2.976 ^0.311 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.354 ^2.535 ^0.3 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.225 ^2.344 ^0.293 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.326 ^2.968 ^0.289 ~ ~