#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.512 ^2.189 ^-0.037 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.015 ^2.812 ^-0.023 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.264 ^2.373 ^-0.003 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.133 ^2.622 ^0.02 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.494 ^2.808 ^0.045 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.221 ^2.369 ^0.068 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.813 ^2.181 ^0.088 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.269 ^2.805 ^0.101 ~ ~