#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.772 ^1.626 ^0.815 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.535 ^1.785 ^1.238 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.126 ^1.936 ^1.441 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.296 ^2.08 ^1.394 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.607 ^2.213 ^1.156 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.75 ^2.335 ^0.832 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.739 ^2.444 ^0.517 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.623 ^2.539 ^0.269 ~ ~