#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-86.3742f,-59.5495f,129.1853f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-115.284f,-34.6008f,148.1562f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-131.7869f,-8.7705f,151.3348f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-147.5812f,14.8964f,148.0455f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-167.2213f,34.6826f,138.4162f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [165.4908f,48.2042f,120.1077f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [131.7425f,52.7325f,94.7939f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [102.1677f,49.1453f,73.1664f]