#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.463 ^2.617 ^0.106 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.338 ^2.68 ^0.175 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.463 ^2.617 ^0.106 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.694 ^2.102 ^-0.055 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.767 ^2.152 ^-0.001 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.829 ^2.221 ^0.024 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.873 ^2.28 ^0.031 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.885 ^2.303 ^0.025 ~ ~