#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-73.9287f,-36.3606f,52.393f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-75.7443f,-37.3697f,55.3715f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-77.6538f,-38.5536f,58.5113f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-79.1949f,-39.5812f,61.0407f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-79.8308f,-40.0202f,62.0814f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-79.1902f,-39.1692f,60.3255f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-77.7606f,-37.248f,56.3133f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-76.2191f,-35.1667f,51.8656f]