#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function temple_boss:animations/animation.model.attack_6/tree/upper_left_arm_display_64-71
execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]