#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [49.5328f,-33.4855f,-59.5544f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [50.0878f,-34.9594f,-66.5796f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [49.5328f,-33.4855f,-59.5544f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [0.6657f,50.7101f,29.8133f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-3.6648f,56.6831f,29.0056f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-6.5034f,59.8333f,27.9934f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-7.4337f,60.7536f,27.5951f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-6.6856f,60.0176f,27.9178f]