#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [-75.114f,-33.6882f,48.6222f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [-74.9333f,-33.4488f,48.0892f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [-76.2191f,-35.1667f,51.8656f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [-79.8308f,-40.0202f,62.0814f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [-96.2769f,-56.8328f,97.8308f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [177.2732f,-70.7441f,-152.0222f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [112.3592f,-43.5331f,-70.7963f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [81.1094f,-25.4435f,-29.488f]