#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.463 ^2.617 ^0.106 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.19 ^2.806 ^0.016 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.031 ^2.626 ^-0.034 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.01 ^2.75 ^-0.048 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.062 ^2.819 ^-0.045 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.181 ^2.626 ^-0.034 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.369 ^2.385 ^-0.023 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.098 ^2.226 ^-0.016 ~ ~