#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [59.0131f,-37.2046f,1.3524f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [57.5943f,-54.9407f,2.2283f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [52.8478f,-75.3739f,6.3203f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-107.9906f,-81.3177f,166.3169f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-118.0381f,-56.2693f,175.1894f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-120.6481f,-29.152f,176.0063f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-123.165f,-0.3693f,175.4781f]