#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.135 ^2.779 ^0.287 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.082 ^2.848 ^0.29 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.135 ^2.779 ^0.287 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.881 ^2.725 ^0.142 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.84 ^2.77 ^0.106 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.789 ^2.832 ^0.087 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.748 ^2.888 ^0.082 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.734 ^2.913 ^0.086 ~ ~