#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.temple_boss.root] at @s run function temple_boss:animations/animation.model.walk/zzz/conditional/22
execute if score #execute aj.i matches 0 run function temple_boss:animations/animation.model.walk/zzz/conditional/23