#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [3.6566f,-0.9571f,3.4492f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [4.0212f,-0.942f,3.3963f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [2.5f,-0.89f,3.21f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [2.1991f,-0.7826f,2.8233f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [1.7593f,-0.626f,2.2585f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [1.25f,-0.4448f,1.6047f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [0.7407f,-0.2636f,0.9509f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [0.3009f,-0.1071f,0.3863f]