#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0 ^4.009 ^1.063 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0 ^2.628 ^1.063 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0 ^1.226 ^1.063 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0 ^0.01 ^1.063 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0 ^-0.813 ^1.063 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0 ^-1.209 ^1.067 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0 ^-1.336 ^1.076 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0 ^-1.278 ^1.086 ~ ~