#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.022 ^4.324 ^1.354 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.021 ^2.916 ^1.377 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.019 ^1.479 ^1.4 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.018 ^0.233 ^1.415 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.017 ^-0.604 ^1.417 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.017 ^-1.004 ^1.418 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.017 ^-1.142 ^1.426 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.017 ^-1.097 ^1.435 ~ ~