#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [26.7396f,-0.8941f,3.2151f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [31.3615f,-0.8941f,3.2151f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [36.7419f,-0.8941f,3.2151f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [41.0612f,-0.894f,3.215f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [42.5f,-0.8938f,3.2148f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [42.4289f,-0.9037f,3.2513f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [43.3534f,-0.9257f,3.3322f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [44.5482f,-0.9475f,3.413f]