#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-10.9492f,-0.9407f,3.3835f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-55.4762f,-0.953f,3.4274f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-95.7211f,-0.959f,3.4491f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-124.1853f,-0.9598f,3.452f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-154.0264f,-0.9564f,3.4397f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [175.484f,-0.9497f,3.4157f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [145.074f,-0.9407f,3.3835f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [115.4718f,-0.9305f,3.3466f]