#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function temple_boss:animations/animation.model.attack_2/tree/bone2_display_0-7
execute if score .this aj.frame matches 8..15 run function temple_boss:animations/animation.model.attack_2/tree/bone2_display_8-15
execute if score .this aj.frame matches 16..23 run function temple_boss:animations/animation.model.attack_2/tree/bone2_display_16-23
execute if score .this aj.frame matches 24..31 run function temple_boss:animations/animation.model.attack_2/tree/bone2_display_24-31
execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [2.5f,-0.8938f,3.2148f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [2.5f,-0.8938f,3.2148f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [2.5f,-0.8938f,3.2148f]