#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^0.632 ^1.09 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^1.447 ^1.089 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^2.311 ^1.082 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^3.135 ^1.073 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^3.831 ^1.066 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^4.312 ^1.063 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^4.551 ^1.063 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^4.617 ^1.063 ~ ~