#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.008 ^0.904 ^0.618 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.004 ^1.525 ^0.55 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.018 ^2.157 ^0.561 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.029 ^2.761 ^0.679 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.034 ^3.314 ^0.899 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.03 ^3.78 ^1.172 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.018 ^4.141 ^1.42 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.003 ^4.43 ^1.574 ~ ~