#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.013 ^4.636 ^1.602 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.024 ^4.748 ^1.52 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.03 ^4.784 ^1.373 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.032 ^4.794 ^1.212 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.031 ^4.855 ^1.076 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.027 ^6.036 ^0.92 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.025 ^6.372 ^0.843 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.024 ^5.648 ^0.823 ~ ~