#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.032 ^-0.576 ^1.038 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.031 ^-0.393 ^1.028 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.029 ^-0.275 ^0.984 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.024 ^-0.194 ^0.891 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.018 ^-0.083 ^0.757 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.011 ^0.035 ^0.606 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.006 ^0.142 ^0.462 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.002 ^0.227 ^0.343 ~ ~