#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [11.2464f,-0.1076f,0.387f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [31.1235f,-0.2648f,0.9525f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [52.5209f,-0.4469f,1.6074f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [68.328f,-0.629f,2.2622f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [71.4343f,-0.7862f,2.8278f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [54.7293f,-0.8938f,3.2148f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [28.8045f,-0.9214f,3.3138f]