#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [73.5579f,64.0406f,-4.7125f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [88.3762f,66.0482f,8.674f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [104.1564f,65.7794f,23.2153f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [114.6123f,64.3006f,32.8605f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [116.8371f,63.6519f,34.9336f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [114.5779f,63.574f,32.9211f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [113.0254f,62.7616f,31.5175f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [111.131f,61.572f,29.7069f]