#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [107.9177f,60.2821f,26.5682f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [102.4886f,59.0149f,21.3132f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [94.0201f,57.5985f,13.3066f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [77.7804f,50.0486f,-1.73f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [64.6062f,35.5041f,-12.2557f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [56.8808f,17.2937f,-14.9867f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [51.9639f,-0.3369f,-11.8404f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [47.9592f,-14.1529f,-5.3674f]