#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [50.2541f,-25.884f,-1.7244f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [62.2938f,-29.2636f,-8.8609f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [75.5094f,-30.9392f,-18.6485f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [83.8677f,-32.0591f,-27.6376f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [82.5534f,-37.1135f,-32.4107f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [64.211f,-50.6386f,-25.1455f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [42.7908f,-61.2743f,-11.7616f]