#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [114.0178f,50.9402f,54.9474f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [74.6936f,66.0627f,20.6611f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [21.7515f,63.5409f,-28.0764f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-4.0718f,51.1405f,-50.3606f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-15.232f,39.3767f,-58.7005f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-23.8085f,24.8816f,-63.7927f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-27.3669f,17.4043f,-65.4997f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-28.3167f,15.6306f,-66.1029f]