#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.362 ^3.998 ^0.246 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.366 ^2.683 ^0.25 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.37 ^1.356 ^0.26 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.374 ^0.199 ^0.274 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.375 ^-0.604 ^0.28 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.375 ^-1.001 ^0.284 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.376 ^-1.117 ^0.297 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.377 ^-1.043 ^0.311 ~ ~