#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [116.4928f,42.6725f,-78.4437f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [113.6549f,17.2325f,-77.048f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [108.0367f,-4.7074f,-71.76f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [88.937f,-13.45f,-47.0791f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [70.3638f,5.9474f,-22.4831f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [61.6967f,35.333f,-14.3672f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [65.2391f,56.9786f,-11.2961f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [65.2297f,60.5747f,-11.7731f]