#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.219 ^-1.063 ^-0.031 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.211 ^-1.085 ^-0.095 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.202 ^-1.089 ^-0.205 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.197 ^-1.061 ^-0.264 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.194 ^-1.037 ^-0.245 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.186 ^-1.068 ^-0.171 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.165 ^-1.165 ^0.016 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.154 ^-0.936 ^0.216 ~ ~