#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.481 ^5.598 ^0.627 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.457 ^5.202 ^0.215 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.432 ^4.706 ^-0.017 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.41 ^4.273 ^-0.086 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.394 ^4.025 ^-0.056 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.379 ^4.918 ^0.066 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.372 ^5.14 ^0.162 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.371 ^4.389 ^0.192 ~ ~