#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.373 ^-0.449 ^0.766 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.37 ^0.307 ^1.195 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.381 ^1.313 ^1.66 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.409 ^2.509 ^2.031 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.444 ^3.74 ^2.194 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.475 ^4.788 ^2.077 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.494 ^5.465 ^1.697 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.495 ^5.725 ^1.162 ~ ~