#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.412 ^-1.276 ^0.12 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.417 ^-1.294 ^0.044 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.424 ^-1.296 ^-0.088 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.431 ^-1.26 ^-0.158 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.433 ^-1.223 ^-0.127 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.424 ^-1.225 ^-0.016 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.402 ^-1.249 ^0.222 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.385 ^-0.962 ^0.443 ~ ~