#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [91.0835f,-4.4749f,0.9396f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [66.1648f,-4.3641f,2.7759f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [44.2306f,-3.506f,3.9248f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [26.0006f,-2.4615f,4.2866f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [12.1634f,-1.6063f,4.0608f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-3.7138f,-1.013f,3.5387f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-11.5523f,-0.7851f,2.851f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-13.1917f,-0.6993f,2.178f]