#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.372 ^3.269 ^0.166 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.375 ^1.963 ^0.111 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.379 ^0.652 ^0.054 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.383 ^-0.488 ^0.015 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.384 ^-1.285 ^0.003 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.383 ^-1.682 ^0.01 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.381 ^-1.792 ^0.016 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.38 ^-1.711 ^0.02 ~ ~