#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [6.2222f,-2.7033f,-2.8647f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [14.8405f,-2.8898f,-4.1522f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [23.4728f,-1.6013f,-5.3582f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [27.3275f,0.6064f,-5.7762f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [21.591f,2.2548f,-5.9171f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [1.2148f,1.4578f,-6.8974f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-19.7452f,1.4198f,-7.8793f]