#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.329 ^5.604 ^0.632 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.35 ^5.209 ^0.234 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.374 ^4.717 ^0.013 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.394 ^4.289 ^-0.05 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.408 ^4.045 ^-0.016 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.422 ^4.943 ^0.109 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.427 ^5.166 ^0.205 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.428 ^4.412 ^0.234 ~ ~