#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.379 ^-1.535 ^0.021 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.381 ^-1.361 ^0.016 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.385 ^-1.285 ^0.003 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.392 ^-1.292 ^-0.016 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.402 ^-1.303 ^-0.028 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.41 ^-1.31 ^-0.017 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.415 ^-1.308 ^0.02 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.415 ^-1.294 ^0.073 ~ ~