#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [8.3585f,-5.3095f,-1.3643f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [8.1335f,-5.2555f,-0.9793f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [7.216f,-3.4188f,-0.4462f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [5.206f,-2.3f,0.4401f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [2.9502f,-0.8131f,1.1345f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [1.2246f,0.4549f,1.0706f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [0.284f,0.9819f,0.1448f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-0.0191f,0.6748f,-1.2628f]