#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.267 ^3.453 ^-0.026 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.263 ^2.163 ^-0.068 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.257 ^0.869 ^-0.108 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.253 ^-0.258 ^-0.133 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.251 ^-1.051 ^-0.139 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.252 ^-1.448 ^-0.135 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.251 ^-1.556 ^-0.129 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.251 ^-1.472 ^-0.124 ~ ~