#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [68.205f,-38.1003f,62.4026f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [56.9813f,-15.6551f,65.6558f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [47.0381f,3.3179f,63.1228f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [34.8428f,11.1836f,50.6942f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [25.2789f,3.5526f,39.5058f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [17.559f,-7.4961f,38.0116f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [16.0867f,-16.6063f,42.0612f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [15.0157f,-17.5499f,43.4438f]