#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.292 ^-0.455 ^0.544 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.293 ^0.235 ^0.991 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.281 ^1.168 ^1.507 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.254 ^2.31 ^1.978 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.217 ^3.538 ^2.262 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.18 ^4.643 ^2.255 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.153 ^5.426 ^1.943 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.144 ^5.808 ^1.418 ~ ~