#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-41.2457f,49.0532f,-7.563f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-80.88f,44.6573f,-33.4982f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-110.2848f,28.6415f,-51.1753f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-129.9326f,5.8966f,-59.5493f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-144.2243f,-20.1833f,-60.8237f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-160.9127f,-46.6416f,-53.0565f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [157.686f,-66.7805f,-17.2598f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [92.2233f,-60.3041f,43.6873f]