#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-34.752f,24.2789f,69.4217f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-57.2263f,42.8506f,61.1427f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-91.9661f,59.6586f,38.026f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-150.7558f,63.7387f,-14.3497f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [168.0013f,46.3115f,-48.66f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [148.9672f,21.4862f,-59.3836f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [135.6705f,-4.6745f,-61.3223f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [121.5605f,-29.8375f,-57.1088f]