#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.152 ^5.787 ^0.834 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.173 ^5.461 ^0.339 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.199 ^4.991 ^0.014 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.222 ^4.551 ^-0.136 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.24 ^4.281 ^-0.165 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.259 ^5.131 ^-0.101 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.267 ^5.325 ^-0.029 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.269 ^4.566 ^-0.005 ~ ~