#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [45f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [46.0689f,3.7077f,0.8219f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [51.0984f,8.3647f,3.9133f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [55.6985f,12.6774f,9.8818f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [55.2179f,16.461f,17.1907f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [44.9332f,22.2447f,22.5461f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [18.8983f,33.3871f,19.2033f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-6.0804f,42.9571f,11.69f]