#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.371 ^-0.827 ^0.332 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.371 ^-0.65 ^0.323 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.374 ^-0.562 ^0.291 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.378 ^-0.545 ^0.228 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.381 ^-0.521 ^0.147 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.383 ^-0.495 ^0.07 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.382 ^-0.468 ^0.012 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.378 ^-0.44 ^-0.023 ~ ~