#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.413 ^0.188 ^0.435 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.422 ^0.791 ^0.654 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.424 ^1.533 ^0.973 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.416 ^2.391 ^1.341 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.397 ^3.306 ^1.669 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.372 ^4.149 ^1.858 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.348 ^4.8 ^1.846 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.331 ^5.212 ^1.64 ~ ~