#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,37.5f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [3.8224f,-2.5683f,41.2277f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [10.7614f,-9.3213f,46.2186f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [15.9938f,-17.735f,51.3769f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [16.0333f,-23.6618f,57.0084f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [9.156f,-21.7217f,63.7955f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-3.5778f,-6.0283f,69.5081f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-17.256f,7.4529f,71.5416f]