#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^1.74 ^5.443 ^1.332 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^1.74 ^5.29 ^0.854 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^1.725 ^4.897 ^0.551 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^1.563 ^4.214 ^0.718 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^1 ^3.758 ^1.094 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.344 ^4.658 ^1.163 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.029 ^4.804 ^0.961 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.013 ^4.051 ^0.929 ~ ~