#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.812 ^-1.603 ^0.264 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.858 ^-1.639 ^0.193 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.934 ^-1.672 ^0.031 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^1.042 ^-1.654 ^-0.08 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^1.176 ^-1.598 ^-0.063 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^1.316 ^-1.521 ^0.09 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^1.441 ^-1.37 ^0.377 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^1.544 ^-0.881 ^0.53 ~ ~