#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [78.0527f,4.8472f,146.1409f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [93.8951f,20.9731f,150.7356f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [110.5839f,31.0365f,163.4002f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [84.543f,30.6373f,168.9276f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [41.5122f,16.4702f,158.4022f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [20.8418f,7.6599f,143.0304f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [12.7801f,6.5123f,136.4295f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [12.3264f,7.3347f,136.56f]