#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [135.8071f,37.6802f,-113.2411f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [138.3825f,44.3063f,-115.6734f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [140.1544f,50.1819f,-121.0611f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [143.6525f,51.0589f,-127.2241f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [154.8167f,44.068f,-129.3193f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [176.662f,27.0388f,-127.7576f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-165.1446f,15.0349f,-131.9693f]