#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.609 ^-0.944 ^0.828 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.622 ^-0.767 ^0.814 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.64 ^-0.67 ^0.776 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.69 ^-0.657 ^0.683 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.744 ^-0.657 ^0.556 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.777 ^-0.678 ^0.429 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.776 ^-0.711 ^0.332 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.749 ^-0.741 ^0.276 ~ ~