#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-43.3375f,50.9816f,-10.2924f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-83.8085f,45.053f,-37.6492f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-111.9052f,27.4686f,-54.6196f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-130.1538f,3.677f,-62.199f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-143.4014f,-23.0235f,-63.0579f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-159.6096f,-49.8809f,-54.802f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [154.4394f,-69.6999f,-13.7654f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [87.4018f,-60.2951f,49.2369f]