#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.938 ^0.39 ^0.41 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.926 ^0.98 ^0.487 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.91 ^1.614 ^0.7 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.888 ^2.305 ^1.046 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.862 ^3.062 ^1.465 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.834 ^3.829 ^1.825 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.809 ^4.511 ^1.993 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.792 ^5.038 ^1.912 ~ ~