#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.79 ^5.328 ^1.628 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.799 ^5.364 ^1.256 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.814 ^5.219 ^0.918 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.827 ^4.955 ^0.729 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.788 ^4.753 ^0.708 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.706 ^5.712 ^0.726 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.644 ^5.935 ^0.758 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.634 ^5.193 ^0.764 ~ ~