#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.423 ^3.589 ^0.571 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.415 ^2.241 ^0.53 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.412 ^0.886 ^0.492 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.411 ^-0.288 ^0.468 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.412 ^-1.095 ^0.464 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.414 ^-1.49 ^0.474 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.418 ^-1.605 ^0.488 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.425 ^-1.53 ^0.503 ~ ~