#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.623 ^4.045 ^0.769 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.613 ^2.687 ^0.774 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.604 ^1.316 ^0.781 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.598 ^0.127 ^0.79 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.594 ^-0.681 ^0.796 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.593 ^-1.068 ^0.802 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.595 ^-1.182 ^0.815 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.6 ^-1.112 ^0.826 ~ ~