#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.765 ^-0.731 ^0.123 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.773 ^-0.766 ^0.08 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.785 ^-0.801 ^0.016 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.801 ^-0.807 ^-0.001 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.82 ^-0.795 ^0.036 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.831 ^-0.781 ^0.08 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.826 ^-0.784 ^0.13 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.819 ^-0.511 ^0.187 ~ ~