#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.869 ^5.588 ^1.361 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.877 ^5.48 ^0.867 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.885 ^5.164 ^0.485 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.91 ^4.704 ^0.376 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.803 ^4.383 ^0.501 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.591 ^5.29 ^0.596 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.456 ^5.488 ^0.597 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.436 ^4.736 ^0.598 ~ ~