#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-180f,-36f,180f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-180f,-27f,180f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-180f,-18f,180f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-180f,-9f,180f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-180f,0f,180f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-180f,9f,180f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-180f,18f,180f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-180f,27f,180f]