#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [0f,72f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [0f,63f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [0f,54f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [0f,45f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [0f,36f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [0f,27f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [0f,18f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [0f,9f,0f]