#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function temple_boss:animations/animation.model.test/tree/bone_display_0-7
execute if score .this aj.frame matches 8..15 run function temple_boss:animations/animation.model.test/tree/bone_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [170.4551f,-78.6367f,-157.4132f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [172.8413f,-74.6025f,-163.0599f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [175.2275f,-70.5683f,-168.7066f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [177.6138f,-66.5342f,-174.3533f]