#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [12.1269f,-7.2645f,29.9084f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [12.1269f,-7.2645f,29.9084f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [12.1269f,-7.2645f,29.9084f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [12.1269f,-7.2645f,29.9084f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [12.1269f,-7.2645f,29.9084f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [12.1269f,-7.2645f,29.9084f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [12.1269f,-7.2645f,29.9084f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [12.1269f,-7.2645f,29.9084f]