#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]