#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-10.8278f,-19.843f,-23.1006f]