#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..40 run function temple_boss:animations/animation.model.test/tree/upper_left_arm_display_0-40