#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.temple_boss.bone.bone] ArmorItems[-1].tag.CustomModelData set value 1
data modify entity @s[tag=aj.temple_boss.bone.left_arm] ArmorItems[-1].tag.CustomModelData set value 2
data modify entity @s[tag=aj.temple_boss.bone.upper_left_arm] ArmorItems[-1].tag.CustomModelData set value 3
data modify entity @s[tag=aj.temple_boss.bone.spear] ArmorItems[-1].tag.CustomModelData set value 4
data modify entity @s[tag=aj.temple_boss.bone.right_arm] ArmorItems[-1].tag.CustomModelData set value 5
data modify entity @s[tag=aj.temple_boss.bone.upper_right_arm] ArmorItems[-1].tag.CustomModelData set value 6
data modify entity @s[tag=aj.temple_boss.bone.right_leg] ArmorItems[-1].tag.CustomModelData set value 7
data modify entity @s[tag=aj.temple_boss.bone.lower_right_leg] ArmorItems[-1].tag.CustomModelData set value 8
data modify entity @s[tag=aj.temple_boss.bone.left_leg] ArmorItems[-1].tag.CustomModelData set value 9
data modify entity @s[tag=aj.temple_boss.bone.lower_left_leg] ArmorItems[-1].tag.CustomModelData set value 10
data modify entity @s[tag=aj.temple_boss.bone.head] ArmorItems[-1].tag.CustomModelData set value 11
data modify entity @s[tag=aj.temple_boss.bone.bone2] ArmorItems[-1].tag.CustomModelData set value 12