#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.temple_boss.animation.model.rotate.loopMode matches 0 run function temple_boss:animations/animation.model.rotate/stop
execute if score @s aj.temple_boss.animation.model.rotate.loopMode matches 1 run function temple_boss:animations/animation.model.rotate/pause
execute if score @s aj.temple_boss.animation.model.rotate.loopMode matches 2 run function temple_boss:animations/animation.model.rotate/zzz/execute/17