#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function temple_boss:animations/animation.model.idle/tree/bone2_root_64-71
execute if score .this aj.frame matches 72..79 run function temple_boss:animations/animation.model.idle/tree/bone2_root_72-79
execute if score .this aj.frame matches 80..87 run function temple_boss:animations/animation.model.idle/tree/bone2_root_80-87
execute if score .this aj.frame matches 88 run tp @s ^0 ^-1.599 ^0.343 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^0 ^-1.578 ^0.362 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^0 ^-1.563 ^0.375 ~ ~