#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.077 ^0.096 ^0.459 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.102 ^0.082 ^0.449 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.127 ^0.069 ^0.438 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.149 ^0.058 ^0.427 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.167 ^0.048 ^0.416 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.18 ^0.04 ^0.407 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.185 ^0.033 ^0.401 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.105 ^0.026 ^0.423 ~ ~