#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.109 ^-0.05 ^0.371 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.243 ^0.007 ^0.355 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.302 ^0.05 ^0.343 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.3 ^0.048 ^0.343 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.294 ^0.042 ^0.344 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.285 ^0.033 ^0.345 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.272 ^0.022 ^0.347 ~ ~