#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run data modify entity @s Pose.Head set value [0.9863f,-13.4985f,-20.2624f]
execute if score .this aj.frame matches 129 run data modify entity @s Pose.Head set value [1.0039f,-15.5355f,-20.6242f]
execute if score .this aj.frame matches 130 run data modify entity @s Pose.Head set value [1.01f,-16.98f,-20.75f]
execute if score .this aj.frame matches 131 run data modify entity @s Pose.Head set value [0.9863f,-18.4035f,-20.2624f]
execute if score .this aj.frame matches 132 run data modify entity @s Pose.Head set value [0.9211f,-18.3658f,-18.924f]
execute if score .this aj.frame matches 133 run data modify entity @s Pose.Head set value [0.8237f,-17.1547f,-16.9216f]
execute if score .this aj.frame matches 134 run data modify entity @s Pose.Head set value [0.703f,-15.0581f,-14.442f]
execute if score .this aj.frame matches 135 run data modify entity @s Pose.Head set value [0.5681f,-12.3638f,-11.6719f]