#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^-0.106 ^-0.045 ^0.376 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^-0.13 ^-0.044 ^0.37 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^-0.154 ^-0.044 ^0.362 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^-0.177 ^-0.044 ^0.352 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^-0.2 ^-0.044 ^0.341 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^-0.221 ^-0.045 ^0.329 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^-0.24 ^-0.046 ^0.316 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^-0.257 ^-0.047 ^0.303 ~ ~