#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.052 ^0.036 ^0.436 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.066 ^0.021 ^0.427 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.094 ^-0.001 ^0.409 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.132 ^-0.022 ^0.386 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.178 ^-0.038 ^0.357 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.225 ^-0.046 ^0.326 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.268 ^-0.047 ^0.295 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.303 ^-0.043 ^0.269 ~ ~