#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^0.02 ^-0.099 ^0.343 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^0.013 ^-0.078 ^0.362 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^-0.01 ^-0.058 ^0.379 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^-0.024 ^-0.054 ^0.382 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^-0.041 ^-0.051 ^0.383 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^-0.061 ^-0.048 ^0.382 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^-0.083 ^-0.046 ^0.38 ~ ~