#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [0.5681f,15.7613f,-11.6719f]
execute if score .this aj.frame matches 121 run data modify entity @s Pose.Head set value [0.6367f,11.4942f,-13.0816f]
execute if score .this aj.frame matches 122 run data modify entity @s Pose.Head set value [0.703f,7.2619f,-14.442f]
execute if score .this aj.frame matches 123 run data modify entity @s Pose.Head set value [0.7656f,3.134f,-15.7298f]
execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [0.8237f,-0.8197f,-16.9216f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [0.8759f,-4.5295f,-17.9941f]
execute if score .this aj.frame matches 126 run data modify entity @s Pose.Head set value [0.9211f,-7.9258f,-18.924f]
execute if score .this aj.frame matches 127 run data modify entity @s Pose.Head set value [0.9583f,-10.9386f,-19.6879f]