#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.069 ^-0.07 ^0.363 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.047 ^-0.071 ^0.365 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.028 ^-0.071 ^0.368 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.012 ^-0.068 ^0.371 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.019 ^0.05 ^0.446 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0 ^0.147 ^0.481 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0 ^0.036 ^0.439 ~ ~