#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [4.5412f,-2.4877f,-1.033f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [8.1122f,-2.8569f,-1.1863f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [12.1589f,-2.7986f,-1.1621f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [16.3879f,-2.4294f,-1.0088f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [20.5059f,-1.8657f,-0.7747f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [24.2195f,-1.2244f,-0.5084f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [27.2353f,-0.6219f,-0.2582f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [29.2599f,-0.1749f,-0.0726f]