#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-10.9375f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-25f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-27.5387f,-1.1569f,-0.4806f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-25f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-23.9673f,1.1956f,0.6254f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-22.5083f,2.8525f,1.6426f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-20.7389f,4.8523f,2.9167f]