#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [1.7199f,-4.6988f,-5.7429f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [1.496f,-3.2012f,-3.9126f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [1.1449f,-1.8914f,-2.3117f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [0.6513f,-0.8106f,-0.9907f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-14.0625f,1.4062f,1.7187f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-25f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-12.5f,0f,0f]