#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [28.5698f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [32.0073f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [35.3045f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [38.3466f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [41.0188f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [43.2063f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]