#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]