#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function temple_boss:animations/animation.model.idle/tree/left_arm_display_64-71
execute if score .this aj.frame matches 72..79 run function temple_boss:animations/animation.model.idle/tree/left_arm_display_72-79
execute if score .this aj.frame matches 80..87 run function temple_boss:animations/animation.model.idle/tree/left_arm_display_80-87
execute if score .this aj.frame matches 88 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 89 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]