#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.375 ^-0.169 ^-0.353 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.375 ^-0.17 ^-0.353 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.375 ^-0.172 ^-0.353 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.375 ^-0.175 ^-0.353 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.375 ^-0.179 ^-0.353 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.375 ^-0.185 ^-0.353 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.375 ^-0.191 ^-0.353 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.375 ^-0.198 ^-0.353 ~ ~