#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]