#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function temple_boss:animations/animation.model.idle/tree/left_arm_display_0-63
execute if score .this aj.frame matches 64..90 run function temple_boss:animations/animation.model.idle/tree/left_arm_display_64-90