#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 121 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 122 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 123 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 126 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 127 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]