#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128..135 run function temple_boss:animations/animation.model.idle/tree/lower_left_leg_display_128-135
execute if score .this aj.frame matches 136 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 137 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 138 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 139 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 140 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]