#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]