#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [45f,0f,0f]
execute if score .this aj.frame matches 16..23 run function temple_boss:animations/animation.model.idle/tree/right_arm_display_16-23
execute if score .this aj.frame matches 24..31 run function temple_boss:animations/animation.model.idle/tree/right_arm_display_24-31
execute if score .this aj.frame matches 32..39 run function temple_boss:animations/animation.model.idle/tree/right_arm_display_32-39