#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.375 ^-0.357 ^-0.353 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.375 ^-0.294 ^-0.353 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.375 ^-0.211 ^-0.353 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.375 ^-0.169 ^-0.353 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.375 ^-0.171 ^-0.353 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.375 ^-0.175 ^-0.353 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.375 ^-0.182 ^-0.353 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.375 ^-0.191 ^-0.353 ~ ~