#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^1.091 ^-0.636 ^0.592 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^1.079 ^-0.713 ^0.567 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^1.067 ^-0.786 ^0.539 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^1.054 ^-0.853 ^0.511 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^1.042 ^-0.912 ^0.484 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^1.031 ^-0.962 ^0.46 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^1.023 ^-1.001 ^0.442 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^1.023 ^-1.012 ^0.442 ~ ~