#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]