#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 89 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 91 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 92 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 93 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 94 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 95 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]