#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [148.4517f,6.3262f,-121.0645f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [148.241f,6.661f,-120.925f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [147.65f,7.6079f,-120.5375f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [146.7439f,9.0836f,-119.9546f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [145.5884f,11.0055f,-119.2319f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [144.2468f,13.29f,-118.4242f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [142.7781f,15.8508f,-117.5817f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [141.2359f,18.5983f,-116.7484f]