#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^1.023 ^-1.167 ^0.442 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^1.023 ^-1.165 ^0.442 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^1.023 ^-1.163 ^0.442 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^1.023 ^-1.161 ^0.442 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^1.023 ^-1.158 ^0.442 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^1.023 ^-1.156 ^0.442 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^1.023 ^-1.153 ^0.442 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^1.101 ^-0.638 ^0.613 ~ ~