#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function temple_boss:animations/animation.model.idle/tree/spear_root_64-71
execute if score .this aj.frame matches 72..79 run function temple_boss:animations/animation.model.idle/tree/spear_root_72-79
execute if score .this aj.frame matches 80..87 run function temple_boss:animations/animation.model.idle/tree/spear_root_80-87
execute if score .this aj.frame matches 88 run tp @s ^1.023 ^-2.653 ^0.442 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^1.023 ^-2.653 ^0.442 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^1.023 ^-2.653 ^0.442 ~ ~