#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.815 ^-0.254 ^-0.079 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.815 ^-0.258 ^-0.079 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.814 ^-0.268 ^-0.081 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.813 ^-0.285 ^-0.084 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.811 ^-0.307 ^-0.088 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.808 ^-0.333 ^-0.094 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.804 ^-0.361 ^-0.102 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.8 ^-0.392 ^-0.111 ~ ~