#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.796 ^-0.695 ^-0.193 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.81 ^-0.695 ^-0.236 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.818 ^-0.695 ^-0.274 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.822 ^-0.695 ^-0.3 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.823 ^-0.695 ^-0.31 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.822 ^-0.695 ^-0.303 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.82 ^-0.695 ^-0.286 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.815 ^-0.695 ^-0.26 ~ ~