#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [24.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [25.2216f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [26.427f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [28.2956f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [30.7127f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [33.5634f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [36.7331f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [40.1068f,-22.4774f,1.0351f]