#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128..135 run function temple_boss:animations/animation.model.idle/tree/upper_left_arm_display_128-135
execute if score .this aj.frame matches 136 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 137 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 138 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 139 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 140 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]