#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [43.5698f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [47.0073f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [50.3045f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [53.3466f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [56.0188f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [58.2063f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]