#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 89 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 91 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 92 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 93 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 94 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 95 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]