#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0 ^4.976 ^0.055 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0 ^3.028 ^0.055 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0 ^1.079 ^0.055 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0 ^-0.254 ^0.055 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0 ^-0.254 ^0.055 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0 ^-0.254 ^0.055 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0 ^-0.254 ^0.055 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0 ^-0.254 ^0.055 ~ ~