#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.159 ^-0.002 ^0.371 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.298 ^0.167 ^0.322 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.33 ^0.231 ^0.288 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.349 ^0.309 ^0.23 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.346 ^0.385 ^0.157 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.324 ^0.437 ^0.085 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.303 ^0.453 ^0.029 ~ ~