#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [0f,-24.3426f,-7.4944f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [0f,-26.5064f,-5.6123f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [0f,-25.9654f,-3.8204f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [0f,-21.9083f,-2.2201f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [0f,-13.5237f,-0.9128f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [0f,39.1667f,0.8681f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-180f,86.6667f,-178.8889f]