#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.302 ^0.419 ^-0.003 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.323 ^0.278 ^-0.001 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.294 ^0.06 ^0.037 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.177 ^1.813 ^0.085 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.043 ^4.389 ^0.092 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^6.309 ^0.055 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.199 ^6.535 ^0.127 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.315 ^6.682 ^0.394 ~ ~