#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0 ^6.52 ^0.375 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0 ^6.5 ^0.375 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0 ^6.575 ^0.375 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0 ^6.743 ^0.375 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0 ^6.91 ^0.375 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0 ^6.986 ^0.375 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0 ^6.879 ^0.375 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0 ^6.5 ^0.375 ~ ~