#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.167 ^7.302 ^0.765 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.304 ^7.332 ^0.665 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.379 ^7.31 ^0.191 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^7.253 ^-0.047 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.38 ^7.176 ^0.191 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.307 ^7.086 ^0.665 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.161 ^6.997 ^0.765 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.421 ^6.919 ^0.4 ~ ~