#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-140f,22.5f,-179.0625f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-140f,-46.6667f,-179.4444f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [40f,-64.1667f,0.1736f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [40f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [40f,64.1667f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-140f,46.6667f,-180f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-140f,-22.5f,-180f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-140f,-86.6667f,-180f]