#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-164.0741f,19.8935f,132.8066f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-89.7546f,-27.4405f,128.6529f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [17.2268f,-45.3512f,69.5609f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [88.7243f,-4.8774f,34.3251f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [129.7601f,53.6459f,37.2373f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-80.6168f,49.93f,177.3276f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-85.0904f,-18.7974f,-158.1012f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-161.5378f,-46.6847f,-95.1717f]