#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [18.9813f,-22.2818f,-21.3663f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-8.4363f,-20.174f,-35.091f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-11.1413f,-20.5012f,-32.6344f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-13.6091f,-22.6948f,-28.4f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-16.4418f,-26.1284f,-22.5269f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-20.1672f,-30.0382f,-15.1166f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-25.0045f,-33.4987f,-6.3295f]