#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-30.5693f,-35.5185f,3.3741f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-35.674f,-35.2557f,13.0297f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-38.5906f,-32.2225f,21.3994f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-37.741f,-26.2551f,27.6271f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-32.1449f,-17.2426f,31.6809f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-21.2724f,-4.8764f,34.3219f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [17.2148f,25.8848f,44.8079f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [100.7609f,47.6567f,88.9153f]