#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.284 ^5.52 ^-0.32 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.219 ^5.5 ^-0.344 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.46 ^5.575 ^-0.219 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.518 ^5.743 ^-0.169 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.477 ^5.91 ^-0.205 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.379 ^5.986 ^-0.274 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.27 ^5.879 ^-0.326 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.219 ^5.5 ^-0.344 ~ ~