#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.034 ^-1.067 ^-0.37 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.027 ^-1.07 ^-0.366 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.051 ^-1.069 ^-0.367 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.026 ^0.88 ^-0.373 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.061 ^3.556 ^-0.375 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.219 ^5.5 ^-0.344 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.608 ^5.72 ^-0.044 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.685 ^5.866 ^0.635 ~ ~