#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [178.8304f,29.7333f,-137.8555f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [135.713f,-25.7333f,-140.0224f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [46.3797f,-53.5907f,-74.3577f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-58.4219f,38.5606f,-47.018f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-158.3022f,46.05f,-124.4883f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [150.8779f,-6.387f,-144.8568f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [95.0081f,-51.2519f,-113.9409f]