#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.423 ^-0.36 ^-0.353 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.454 ^-0.31 ^-0.353 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.436 ^-0.317 ^-0.362 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.388 ^-0.334 ^-0.382 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.319 ^-0.356 ^-0.406 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.237 ^-0.379 ^-0.426 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.156 ^-0.398 ^-0.438 ~ ~