#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.478 ^3.991 ^-0.255 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.478 ^2.043 ^-0.255 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.478 ^0.094 ^-0.255 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.478 ^-1.239 ^-0.255 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.478 ^-1.239 ^-0.255 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.478 ^-1.239 ^-0.255 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.478 ^-1.239 ^-0.255 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.478 ^-1.239 ^-0.255 ~ ~