#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,-2.5f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-0.2342f,-2.6128f,-1.2551f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-0.4652f,-5.2246f,1.8152f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-0.8589f,-6.519f,2.1485f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-1.8932f,-9.8829f,3.1075f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-3.3624f,-14.535f,4.6469f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-5.07f,-19.6926f,6.6939f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-6.797f,-24.5765f,9.1033f]