#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.299 ^-1.248 ^-0.312 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.234 ^-1.259 ^-0.317 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.203 ^-1.266 ^-0.316 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.217 ^0.676 ^-0.306 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.287 ^3.346 ^-0.274 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.412 ^5.286 ^-0.193 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.66 ^5.506 ^0.195 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.519 ^5.656 ^0.82 ~ ~