#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.768 ^5.345 ^0.188 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.478 ^5.324 ^-0.255 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.222 ^5.4 ^-0.383 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.144 ^5.567 ^-0.402 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.2 ^5.734 ^-0.39 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.32 ^5.81 ^-0.348 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.431 ^5.704 ^-0.288 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.478 ^5.324 ^-0.255 ~ ~