#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.412 ^-1.315 ^-0.275 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.265 ^-1.332 ^-0.265 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.157 ^-1.322 ^-0.255 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.178 ^-1.325 ^-0.243 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.232 ^-1.331 ^-0.212 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.305 ^-1.337 ^-0.165 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.387 ^-1.337 ^-0.108 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.466 ^-1.331 ^-0.05 ~ ~