#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.183 ^5.75 ^1.057 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.708 ^5.779 ^0.465 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.335 ^5.752 ^-0.244 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.412 ^5.696 ^-0.193 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.691 ^5.618 ^0.499 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.13 ^5.529 ^1.065 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.598 ^5.44 ^0.742 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.591 ^5.362 ^-0.004 ~ ~