#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.219 ^-1.063 ^-0.344 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.07 ^-1.084 ^-0.344 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.048 ^-1.086 ^-0.344 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.026 ^-1.09 ^-0.338 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.031 ^-1.101 ^-0.323 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.11 ^-1.113 ^-0.296 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.199 ^-1.121 ^-0.262 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.286 ^-1.124 ^-0.223 ~ ~