#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,37.5f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-1.8594f,-1.8508f,38.7696f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-3.7189f,-3.7015f,41.9142f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-4.8554f,-4.439f,42.2878f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-7.8217f,-6.3475f,43.3782f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-11.9667f,-8.961f,45.159f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-16.6427f,-11.8093f,47.5466f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-21.1743f,-14.4432f,50.3346f]