#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-38.8725f,-23.2104f,65.469f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-3.7189f,-3.7015f,56.9142f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [13.779f,7.6664f,57.5272f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [18.7862f,10.7658f,58.33f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [15.2009f,8.5588f,57.7279f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [7.4443f,3.6012f,56.9043f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-0.2277f,-1.4215f,56.7581f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-3.7189f,-3.7015f,56.9142f]