#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-24.8263f,-16.461f,53.1788f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-26.8043f,-17.5114f,55.6388f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-26.3077f,-17.2506f,57.2824f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-22.6266f,-15.2575f,57.8518f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-15.2308f,-10.962f,57.4782f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-3.7189f,-3.7015f,56.9142f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [29.8981f,17.0978f,61.8854f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [87.8453f,33.2017f,88.8663f]