#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.624 ^5.52 ^-0.044 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.219 ^5.5 ^-0.344 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.051 ^5.575 ^-0.375 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.127 ^5.743 ^-0.365 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.073 ^5.91 ^-0.373 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.047 ^5.986 ^-0.375 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.166 ^5.879 ^-0.358 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.219 ^5.5 ^-0.344 ~ ~