#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [45f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [46.4576f,-2.86f,16.6165f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [47.5913f,-5.0845f,29.5405f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [46.5241f,-5.7749f,27.1328f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [44.2233f,-7.9538f,21.0369f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [42.2637f,-11.6656f,12.9188f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [41.8634f,-16.3201f,4.3553f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [43.165f,-20.8446f,-3.0755f]