#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-89.9076f,37.9181f,-29.7736f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-149.6284f,64.9365f,-93.0125f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [162.9336f,44.8322f,-142.1239f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [151.8095f,19.6195f,-155.5646f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [146.6129f,1.6316f,-162.5488f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [142.5526f,-6.6626f,-164.1556f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [141.0527f,-4.2466f,-157.657f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [144.3588f,9.8526f,-141.0064f]