#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.983 ^-1.633 ^0.367 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^1.662 ^-0.299 ^0.654 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^1.338 ^0.831 ^0.314 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^1.293 ^1.857 ^-0.144 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^1.319 ^3.189 ^-0.931 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^1.163 ^4.2 ^-1.555 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.478 ^4.956 ^-1.54 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.283 ^5.864 ^-1.156 ~ ~