#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [175.6234f,42.8212f,-94.8343f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [167.3194f,16.0916f,-117.9083f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [154.6249f,20.6009f,-148.5797f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [122.6207f,19.3434f,166.2488f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [83.4297f,-12.3671f,134.9731f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [29.6175f,-60.2611f,161.8006f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-68.8913f,-42.8383f,-91.1691f]