#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^1.505 ^4.706 ^0.255 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.701 ^1.692 ^-0.206 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.157 ^-0.27 ^-0.045 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.431 ^-1.283 ^0.561 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.431 ^-1.283 ^0.561 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.431 ^-1.283 ^0.561 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.431 ^-1.283 ^0.561 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.431 ^-1.283 ^0.561 ~ ~