#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-1.027 ^5.769 ^0.742 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.643 ^5.556 ^-0.189 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.074 ^5.393 ^-0.406 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.802 ^5.305 ^-0.069 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.947 ^5.318 ^1.079 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.513 ^5.495 ^1.793 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-1.753 ^5.847 ^0.308 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.679 ^6.284 ^-1.307 ~ ~