#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-19.3441f,6.7449f,-159.6614f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-58.5318f,-76.5591f,-127.4272f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-175.2584f,-14.5368f,-1.407f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-158.5054f,57.7796f,7.5261f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [24.0198f,54.3435f,173.6492f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [47.5218f,-16.0335f,-178.7887f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-7.5731f,-80.6107f,-103.6091f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-83.2911f,-20.857f,-18.7173f]