#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.182 ^6.238 ^-0.81 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.864 ^6.332 ^-0.392 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^1.014 ^6.485 ^0.033 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.902 ^6.717 ^0.223 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.714 ^6.911 ^0.221 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.552 ^6.978 ^0.147 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.498 ^6.849 ^0.083 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.628 ^6.389 ^0.037 ~ ~