#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.735 ^-0.86 ^0.274 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.733 ^-0.859 ^0.294 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.751 ^-0.835 ^0.289 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.801 ^1.156 ^0.238 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.797 ^3.855 ^0.119 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.737 ^5.82 ^-0.067 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.309 ^6.065 ^-0.443 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.481 ^6.213 ^-0.359 ~ ~