#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.274 ^6.212 ^0.907 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.625 ^6.157 ^0.467 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.439 ^6.092 ^-0.208 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.383 ^6.028 ^-0.373 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.941 ^5.971 ^0.475 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.153 ^5.958 ^1.427 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-1.063 ^6.013 ^0.845 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.88 ^6.12 ^-0.456 ~ ~