#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-94.3857f,-52.822f,66.754f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-97.1254f,-49.0612f,75.6083f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-94.9289f,-45.536f,80.7564f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-87.2537f,-42.9544f,82.029f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-73.1814f,-41.297f,78.6589f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-51.7242f,-38.9446f,69.4206f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [0.9777f,-20.4648f,44.3946f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [49.6981f,27.5723f,34.9556f]