#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [63.9864f,-15.3783f,-76.1549f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [54.7417f,72.8864f,-51.4546f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-78.5908f,32.0898f,-165.6951f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-47.1774f,28.5222f,-171.4755f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-47.1774f,28.5222f,-171.4755f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-47.1774f,28.5222f,-171.4755f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-47.1774f,28.5222f,-171.4755f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-47.1774f,28.5222f,-171.4755f]