#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [124.6693f,6.022f,-105.6835f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [83.2964f,-7.7909f,-118.6919f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [55.6646f,-27.366f,-119.0788f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [28.8159f,-43.2241f,-110.574f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [3.135f,-49.5102f,-97.8237f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-10.8842f,-48.5342f,-89.0021f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-8.0547f,-46.4336f,-84.7322f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [12.0956f,-43.6085f,-82.5762f]