#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players add .aj.animation aj.temple_boss.animating 0
scoreboard players add .aj.anim_loop aj.temple_boss.animating 0
scoreboard players add .noScripts aj.i 0