#Project generated by Animated Java (https://animated-java.dev/)

scoreboard objectives add aj.i dummy
scoreboard objectives add aj.id dummy
scoreboard objectives add aj.frame dummy
scoreboard objectives add aj.temple_boss.animating dummy
scoreboard objectives add aj.temple_boss.animation.model.test.loopMode dummy
scoreboard objectives add aj.temple_boss.animation.model.walk.loopMode dummy
scoreboard objectives add aj.temple_boss.animation.model.idle.loopMode dummy
scoreboard objectives add aj.temple_boss.animation.model.attack_1.loopMode dummy
scoreboard objectives add aj.temple_boss.animation.model.attack_2.loopMode dummy
scoreboard objectives add aj.temple_boss.animation.model.attack_3.loopMode dummy
scoreboard objectives add aj.temple_boss.animation.model.attack_4.loopMode dummy
scoreboard objectives add aj.temple_boss.animation.model.attack_5.loopMode dummy
scoreboard objectives add aj.temple_boss.animation.model.attack_6.loopMode dummy
function temple_boss:reset_animation_flags
scoreboard players set #uninstall aj.i 0
scoreboard players set .aj.temple_boss.framerate aj.i 1