#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set .aj.animation aj.temple_boss.animating 0
scoreboard players set .aj.anim_loop aj.temple_boss.animating 0
scoreboard players set .noScripts aj.i 0