#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#temple_boss:bone_entities,tag=aj.temple_boss.bone] if score @s aj.id = .this aj.id run function temple_boss:zzz/execute/29