#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.temple_boss.anim.animation.model.test] at @s run function temple_boss:animations/animation.model.test/next_frame
execute if entity @s[tag=aj.temple_boss.anim.animation.model.walk] at @s run function temple_boss:animations/animation.model.walk/next_frame
execute if entity @s[tag=aj.temple_boss.anim.animation.model.idle] at @s run function temple_boss:animations/animation.model.idle/next_frame
execute if entity @s[tag=aj.temple_boss.anim.animation.model.attack_1] at @s run function temple_boss:animations/animation.model.attack_1/next_frame
execute if entity @s[tag=aj.temple_boss.anim.animation.model.attack_2] at @s run function temple_boss:animations/animation.model.attack_2/next_frame
execute if entity @s[tag=aj.temple_boss.anim.animation.model.attack_3] at @s run function temple_boss:animations/animation.model.attack_3/next_frame
execute if entity @s[tag=aj.temple_boss.anim.animation.model.attack_4] at @s run function temple_boss:animations/animation.model.attack_4/next_frame
execute if entity @s[tag=aj.temple_boss.anim.animation.model.attack_5] at @s run function temple_boss:animations/animation.model.attack_5/next_frame
execute if entity @s[tag=aj.temple_boss.anim.animation.model.attack_6] at @s run function temple_boss:animations/animation.model.attack_6/next_frame
scoreboard players operation @s aj.temple_boss.animating = .aj.animation aj.temple_boss.animating