#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.temple_boss.bone.bone] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.temple_boss.bone.left_arm] Pose.Head set value [44.794f,-22.477f,1.035f]
data modify entity @s[tag=aj.temple_boss.bone.upper_left_arm] Pose.Head set value [59.794f,-22.477f,1.035f]
data modify entity @s[tag=aj.temple_boss.bone.spear] Pose.Head set value [132.332f,34.971f,-113.218f]
data modify entity @s[tag=aj.temple_boss.bone.right_arm] Pose.Head set value [45f,0f,0f]
data modify entity @s[tag=aj.temple_boss.bone.upper_right_arm] Pose.Head set value [45f,0f,0f]
data modify entity @s[tag=aj.temple_boss.bone.right_leg] Pose.Head set value [0f,0f,37.5f]
data modify entity @s[tag=aj.temple_boss.bone.lower_right_leg] Pose.Head set value [0f,0f,-2.5f]
data modify entity @s[tag=aj.temple_boss.bone.left_leg] Pose.Head set value [-16.106f,-12.017f,-35.794f]
data modify entity @s[tag=aj.temple_boss.bone.lower_left_leg] Pose.Head set value [2.493f,-1.819f,-2.201f]
data modify entity @s[tag=aj.temple_boss.bone.head] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.temple_boss.bone.bone2] Pose.Head set value [0f,0f,0f]
tp @s ~ ~ ~ ~ ~