#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0 ^0.171 ^0.375 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0 ^0.353 ^0.375 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0 ^0.437 ^0.375 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0 ^0.371 ^0.375 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0 ^0.218 ^0.375 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0 ^0.05 ^0.375 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0 ^-0.063 ^0.375 ~ ~