#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.181 ^0.27 ^0.375 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.18 ^0.529 ^0.375 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.179 ^0.649 ^0.375 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.18 ^0.541 ^0.375 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.18 ^0.301 ^0.375 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.181 ^0.053 ^0.375 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.18 ^-0.078 ^0.375 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.178 ^-0.021 ^0.375 ~ ~