#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [0f,0f,-23.75f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [0f,0f,-26.3281f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [0f,0f,-27.5f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [0f,0f,-26.9727f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [0f,0f,-25.4687f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [0f,0f,-23.1055f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [0f,0f,-20f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [0f,0f,-18.4162f]