#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [0f,0f,6.0893f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [0f,0f,3.1473f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [0f,0f,1.5595f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [0f,0f,1.619f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [0f,0f,2.6031f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [0f,0f,4.3945f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [0f,0f,5.9298f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [0f,0f,5.3854f]