#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.138 ^0.486 ^-0.047 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.152 ^0.661 ^-0.047 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.159 ^0.742 ^-0.047 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.156 ^0.677 ^-0.047 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.148 ^0.529 ^-0.047 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.135 ^0.366 ^-0.047 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.118 ^0.26 ^-0.047 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.109 ^0.263 ^-0.047 ~ ~