#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [0f,0f,4.7597f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [0f,0f,4.079f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [0f,0f,3.3699f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [0f,0f,2.6588f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [0f,0f,1.9722f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [0f,0f,1.3366f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [0f,0f,0.7783f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [0f,0f,0.324f]