#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [35.8486f,-2.4883f,-92.4084f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [35.9396f,-2.6916f,-90.9318f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [36.0634f,-2.9683f,-89.2885f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [36.218f,-3.3137f,-86.477f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [36.4013f,-3.7232f,-82.6387f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [36.6112f,-4.1922f,-78.8433f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [36.8456f,-4.7161f,-76.1602f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [37.1026f,-5.2903f,-75.4832f]