#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.493 ^-0.96 ^-0.344 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.459 ^-0.978 ^-0.344 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.421 ^-0.996 ^-0.344 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.381 ^-1.013 ^-0.344 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.342 ^-1.028 ^-0.344 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.304 ^-1.041 ^-0.344 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.269 ^-1.051 ^-0.344 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.24 ^-1.058 ^-0.344 ~ ~