#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-16.2452f,-9.1706f,-61.5293f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-16.2226f,-9.6358f,-57.8257f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-16.2011f,-10.0754f,-54.0477f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-16.1811f,-10.4866f,-50.3019f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-16.1626f,-10.8666f,-46.6952f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-16.1457f,-11.2125f,-43.3343f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-16.1306f,-11.5215f,-40.3259f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-16.1175f,-11.7907f,-37.7768f]