#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.487 ^-0.003 ^-0.353 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.494 ^0.2 ^-0.353 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.497 ^0.294 ^-0.353 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.496 ^0.223 ^-0.353 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.492 ^0.058 ^-0.353 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.485 ^-0.13 ^-0.353 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.474 ^-0.269 ^-0.353 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.468 ^-0.282 ^-0.353 ~ ~