#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-16.4549f,-4.8701f,-82.7815f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-16.4272f,-5.4375f,-83.5149f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-16.3997f,-6.002f,-82.8513f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-16.3725f,-6.5609f,-80.507f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-16.3456f,-7.1112f,-77.2138f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-16.3194f,-7.6502f,-73.0981f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-16.2938f,-8.175f,-68.2864f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-16.269f,-8.6827f,-65.0518f]