#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [40.0864f,-11.9577f,-56.5908f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [40.4547f,-12.7805f,-56.519f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [40.8227f,-13.6029f,-55.0427f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [41.1885f,-14.4202f,-51.8837f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [41.5498f,-15.2277f,-47.7795f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [41.9048f,-16.0208f,-42.8621f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [42.2512f,-16.7949f,-37.2637f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [42.5871f,-17.5455f,-33.2629f]