#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.888 ^-0.679 ^-0.188 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.925 ^-0.464 ^-0.189 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.941 ^-0.368 ^-0.189 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.933 ^-0.451 ^-0.189 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.91 ^-0.635 ^-0.19 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.873 ^-0.847 ^-0.19 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.821 ^-1.013 ^-0.19 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.793 ^-1.042 ^-0.19 ~ ~