#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.757 ^-1.074 ^-0.191 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.715 ^-1.108 ^-0.191 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.668 ^-1.142 ^-0.191 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.619 ^-1.174 ^-0.192 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.57 ^-1.203 ^-0.192 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.522 ^-1.228 ^-0.192 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.478 ^-1.249 ^-0.193 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.441 ^-1.265 ^-0.193 ~ ~