#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [8.3877f,8.0201f,-62.9124f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [8.1335f,7.6016f,-63.9385f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [7.8694f,7.1659f,-63.4929f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [7.597f,6.7154f,-60.6469f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [7.3177f,6.2526f,-56.3469f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [7.033f,5.7799f,-52.0079f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [6.7444f,5.2998f,-49.0453f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [6.4532f,4.8147f,-48.4054f]