#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,-2.5f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0f,0f,-1.4844f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [0f,0f,1.4844f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0f,0f,2.5f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-0.0213f,-0.0159f,2.8354f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-0.0682f,-0.0509f,3.0177f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-0.1151f,-0.0858f,3.0611f]