#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.295 ^-0.508 ^-0.344 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.281 ^-0.19 ^-0.344 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.268 ^-0.051 ^-0.344 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.238 ^-0.209 ^-0.344 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.194 ^-0.552 ^-0.344 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.154 ^-0.901 ^-0.344 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.136 ^-1.078 ^-0.344 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.157 ^-0.975 ^-0.344 ~ ~