#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,37.5f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0f,0f,38.5156f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0f,0f,40f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [0f,0f,41.4844f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0f,0f,42.5f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-0.0265f,0.0015f,42.8354f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-0.085f,0.0049f,43.0176f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-0.1434f,0.0083f,43.061f]