#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.339 ^0.222 ^-0.353 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.28 ^0.752 ^-0.353 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.215 ^0.416 ^-0.353 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.168 ^-0.114 ^-0.353 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.154 ^-0.451 ^-0.353 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.148 ^-0.558 ^-0.353 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.149 ^-0.362 ^-0.353 ~ ~