#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [2.092f,-0.1207f,38.114f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [1.8706f,-0.108f,37.9677f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [1.5965f,-0.0921f,37.8528f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [1.2903f,-0.0745f,37.7636f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [0.9726f,-0.0561f,37.6942f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [0.6641f,-0.0383f,37.639f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [0.3854f,-0.0222f,37.5921f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [0.1571f,-0.0091f,37.5477f]