#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [1.1469f,-0.0662f,40.5121f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [0.3584f,-0.0207f,41.8788f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [0f,0f,42.5f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [0.3584f,-0.0207f,41.8788f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [1.1469f,-0.0662f,40.5121f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [1.9354f,-0.1117f,39.1454f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [2.2938f,-0.1324f,38.5242f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [1.9354f,-0.1117f,39.1454f]