#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-143.0529f,26.8429f,-135.5798f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-157.0179f,36.9562f,-163.043f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-165.356f,39.7338f,-177.9053f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-157.5657f,38.694f,-164.5048f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-141.2065f,31.9139f,-136.4724f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-128.1687f,21.4335f,-112.7724f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-122.7482f,17.0383f,-102.9536f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-126.8479f,25.467f,-112.2286f]