#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-142.1257f,38.6132f,-138.0329f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-164.8606f,44.6674f,-171.5596f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-177.2813f,44.332f,171.1642f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-169.1026f,46.2282f,-177.0909f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-146.5125f,47.1417f,-146.9752f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-125.7517f,42.1211f,-115.832f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-120.7399f,35.4448f,-98.7533f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-124.6041f,34.9502f,-96.4238f]