#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^1.023 ^-1.153 ^0.442 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^1.283 ^-0.262 ^0.415 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^1.552 ^0.793 ^0.38 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^1.567 ^1.149 ^0.353 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^1.278 ^1.17 ^0.335 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.925 ^1.081 ^0.32 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.701 ^1.035 ^0.308 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.549 ^1.199 ^0.332 ~ ~