#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [62.222f,-57.6165f,-113.2896f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [48.6793f,-44.0778f,-118.0836f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [44.1008f,-38.2583f,-120.8039f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [51.3537f,-44.4353f,-116.9816f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [71.4119f,-56.9695f,-116.5644f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [104.1271f,-66.715f,-127.0556f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [128.7345f,-72.925f,-134.4007f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [128.5327f,-76.1744f,-127.7905f]