#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.658 ^0.157 ^-0.173 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.66 ^0.515 ^-0.198 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.662 ^0.676 ^-0.208 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.68 ^0.505 ^-0.184 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.704 ^0.11 ^-0.131 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.713 ^-0.298 ^-0.082 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.711 ^-0.502 ^-0.061 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.711 ^-0.374 ^-0.082 ~ ~