#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.742 ^0.672 ^-0.021 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.749 ^0.981 ^-0.022 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.757 ^1.112 ^-0.024 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.769 ^0.936 ^-0.027 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.782 ^0.563 ^-0.03 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.795 ^0.184 ^-0.034 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.806 ^-0.011 ^-0.038 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.815 ^0.097 ^-0.042 ~ ~