#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.717 ^-0.757 ^-0.061 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.72 ^-0.069 ^-0.058 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.705 ^0.538 ^-0.052 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.674 ^0.292 ^-0.051 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.648 ^-0.154 ^-0.061 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.645 ^-0.436 ^-0.079 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.649 ^-0.484 ^-0.107 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.654 ^-0.231 ^-0.141 ~ ~