#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.701 ^-0.177 ^-0.131 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.677 ^0.066 ^-0.184 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.662 ^0.176 ^-0.208 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.673 ^0.082 ^-0.187 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.69 ^-0.134 ^-0.141 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.701 ^-0.365 ^-0.092 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.711 ^-0.502 ^-0.061 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.718 ^-0.491 ^-0.052 ~ ~