#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.92 ^0.147 ^-0.097 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.931 ^0.351 ^-0.104 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.942 ^0.436 ^-0.111 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.951 ^0.341 ^-0.118 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.958 ^0.144 ^-0.125 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.959 ^-0.084 ^-0.132 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.954 ^-0.27 ^-0.139 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.95 ^-0.317 ^-0.145 ~ ~