#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.038 ^0.053 ^0.45 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.105 ^0.119 ^0.481 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.038 ^0.053 ^0.45 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.043 ^-0.122 ^0.307 ~ ~