#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.066 ^0.154 ^0.485 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.211 ^0.303 ^0.492 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.076 ^0.161 ^0.487 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.054 ^-0.133 ^0.289 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.102 ^-0.129 ^0.254 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.05 ^-0.126 ^0.3 ~ ~