#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0 ^-0.355 ^0.208 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.4 ^-0.403 ^-0.225 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.558 ^-0.597 ^-0.512 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.4 ^-0.403 ^-0.225 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^-0.355 ^0.208 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.418 ^-0.513 ^0.391 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.631 ^-0.675 ^0.452 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.422 ^-0.503 ^0.372 ~ ~