#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.076 ^0.161 ^0.487 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.211 ^0.303 ^0.492 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.076 ^0.161 ^0.487 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.054 ^-0.133 ^0.289 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.102 ^-0.129 ^0.254 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.05 ^-0.126 ^0.3 ~ ~