#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-0.355 ^0.208 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.406 ^-0.386 ^-0.027 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.617 ^-0.494 ^-0.181 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.406 ^-0.386 ^-0.027 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-0.355 ^0.208 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.422 ^-0.503 ^0.372 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.631 ^-0.675 ^0.452 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.418 ^-0.513 ^0.391 ~ ~