#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0 ^-0.355 ^0.208 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.406 ^-0.386 ^-0.027 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.617 ^-0.494 ^-0.181 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.406 ^-0.386 ^-0.027 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0 ^-0.355 ^0.208 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.383 ^-0.48 ^0.357 ~ ~