#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.038 ^0.053 ^0.45 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.105 ^0.119 ^0.481 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.038 ^0.053 ^0.45 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.05 ^-0.126 ^0.3 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.102 ^-0.129 ^0.254 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.054 ^-0.133 ^0.289 ~ ~