#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-22.6496f,-13.9032f,-30.525f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-19.6832f,-15.3699f,-29.4828f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-22.6496f,-13.9032f,-30.525f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [24.8984f,-11.8079f,-51.6567f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [56.3936f,-12.0174f,-63.2935f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [24.8984f,-11.8079f,-51.6567f]