#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.242 ^-0.52 ^-0.353 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.147 ^-0.559 ^-0.353 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.242 ^-0.52 ^-0.353 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.464 ^-0.291 ^-0.353 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.497 ^-0.206 ^-0.353 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.456 ^-0.306 ^-0.353 ~ ~