#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-54.3313f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-35.7376f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-24.3313f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-35.7376f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-54.3313f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-71.6751f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-81.8313f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-71.6751f]