#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-54.3313f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-37.4563f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-24.3313f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-35.7376f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-54.3313f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-71.6751f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-81.8313f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-71.6751f]