#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [0f,0f,-2.5f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [45.8882f,-5.9851f,7.3798f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [74.7934f,-8.1988f,10.6798f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [45.8882f,-5.9851f,7.3798f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [0f,0f,-2.5f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-33.5062f,-5.0599f,-4.6177f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-49.8447f,-12.607f,-3.0969f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-28.922f,-5.5872f,-1.7513f]