#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-33.4154f,0.0661f,1.6959f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-52.2547f,-2.7152f,3.4502f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-33.4154f,0.0661f,1.6959f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [52.3771f,-24.71f,-17.4504f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [91.0045f,-40.1597f,-40.0165f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [48.9232f,-24.7601f,-16.9646f]