#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-33.4154f,0.0661f,1.6959f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-52.2547f,-2.7152f,3.4502f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-33.4154f,0.0661f,1.6959f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [46.9883f,-22.1945f,-15.0735f]