#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.219 ^-1.063 ^-0.344 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.526 ^-0.941 ^-0.344 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.689 ^-0.82 ^-0.344 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.526 ^-0.941 ^-0.344 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.219 ^-1.063 ^-0.344 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.059 ^-1.085 ^-0.344 ~ ~