#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.469 ^-0.281 ^-0.353 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.503 ^-0.184 ^-0.353 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.469 ^-0.281 ^-0.353 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.265 ^-0.507 ^-0.353 ~ ~