#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [156.7229f,-25.2976f,-101.9852f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-177.1665f,-25.3351f,-106.6405f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-155.7954f,-20.1763f,-112.3932f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-176.1523f,-25.7733f,-107.8083f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [156.7229f,-25.2976f,-101.9852f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [152.9909f,-23.6335f,-115.7629f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [155.0363f,-23.5482f,-127.8757f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [152.9909f,-23.6335f,-115.7629f]