#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [156.7229f,-25.2976f,-101.9852f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-176.2798f,-25.7195f,-109.3804f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-155.7954f,-20.1763f,-112.3932f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [179.6309f,-27.2178f,-104.8073f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [156.7229f,-25.2976f,-101.9852f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-169.289f,-19.0061f,-140.8292f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-137.7954f,-16.6896f,-164.4663f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-169.289f,-19.0061f,-140.8292f]