#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^1.103 ^-0.399 ^-0.131 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^1.133 ^-0.605 ^-0.339 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^1.089 ^-0.734 ^-0.555 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^1.135 ^-0.599 ^-0.344 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^1.103 ^-0.399 ^-0.131 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^1.128 ^-0.162 ^-0.09 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^1.143 ^0.003 ^-0.089 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^1.143 ^-0.173 ^-0.104 ~ ~