#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [156.7229f,-25.2976f,-101.9852f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [179.6309f,-27.2178f,-104.8073f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-155.7954f,-20.1763f,-112.3932f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-177.1665f,-25.3351f,-106.6405f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [156.7229f,-25.2976f,-101.9852f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [161.1238f,-31.3785f,-123.3726f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [170.9958f,-36.0514f,-143.2536f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [161.1238f,-31.3785f,-123.3726f]