#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [156.7229f,-25.2976f,-101.9852f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-176.1523f,-25.7733f,-107.8083f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-155.7954f,-20.1763f,-112.3932f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-175.6401f,-25.9853f,-108.397f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [156.7229f,-25.2976f,-101.9852f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [149.9812f,-20.0361f,-111.2744f]