#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [9.7558f,-21.3931f,30.1006f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-11.6601f,-35.7469f,47.1867f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-35.2458f,-45.6911f,65.3609f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-12.9101f,-35.7469f,47.1867f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [9.7558f,-21.3931f,30.1006f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [13.4694f,-19.8994f,13.4668f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [12.2558f,-21.3931f,2.6006f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [13.4694f,-19.8994f,13.4668f]