#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [9.7558f,-21.3931f,30.1006f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-9.6271f,-32.7523f,46.457f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-35.2458f,-45.6911f,65.3609f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-11.6601f,-35.7469f,47.1867f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [9.7558f,-21.3931f,30.1006f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [2.2194f,-19.8994f,13.4668f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-7.7442f,-21.3931f,2.6006f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [2.2194f,-19.8994f,13.4668f]