#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.717 ^-0.757 ^-0.061 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.898 ^-0.52 ^-0.628 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.783 ^0.016 ^-0.799 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.898 ^-0.52 ^-0.628 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.717 ^-0.757 ^-0.061 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.593 ^-0.636 ^0.078 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.512 ^-0.57 ^0.093 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.593 ^-0.636 ^0.078 ~ ~