#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.717 ^-0.757 ^-0.061 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.898 ^-0.52 ^-0.628 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.783 ^0.016 ^-0.799 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.898 ^-0.52 ^-0.628 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.717 ^-0.757 ^-0.061 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.593 ^-0.636 ^0.078 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.512 ^-0.57 ^0.093 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.593 ^-0.636 ^0.078 ~ ~