#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.717 ^-0.757 ^-0.061 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.896 ^-0.545 ^-0.61 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.783 ^0.016 ^-0.799 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.898 ^-0.52 ^-0.628 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.717 ^-0.757 ^-0.061 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.593 ^-0.636 ^0.078 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.512 ^-0.57 ^0.093 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.593 ^-0.636 ^0.078 ~ ~