#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [9.7558f,-21.3931f,30.1006f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-12.9101f,-35.7469f,47.1867f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-35.2458f,-45.6911f,65.3609f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-13.5351f,-35.7469f,47.1867f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [9.7558f,-21.3931f,30.1006f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [19.0944f,-19.8994f,13.4668f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [22.2558f,-21.3931f,2.6006f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [16.787f,-21.3931f,14.6319f]