#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.744 ^-0.513 ^-0.715 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.562 ^-0.727 ^-0.715 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.419 ^-0.825 ^-0.715 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.562 ^-0.727 ^-0.715 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.744 ^-0.513 ^-0.715 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.844 ^-0.271 ^-0.715 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.868 ^-0.119 ^-0.715 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.837 ^-0.299 ^-0.715 ~ ~