#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [9.7558f,-21.3931f,30.1006f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-12.7538f,-35.7469f,45.4679f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-35.2458f,-45.6911f,65.3609f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-9.6271f,-32.7523f,46.457f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [9.7558f,-21.3931f,30.1006f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-17.2322f,-44.414f,19.5789f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-60.3951f,-46.223f,37.2432f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-17.2322f,-44.414f,19.5789f]