#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-180f,46.7368f,180f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-180f,56.1842f,180f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-180f,65.6316f,180f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-180f,75.0789f,180f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-180f,84.5263f,180f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [0f,86.0263f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [0f,76.5789f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [0f,67.1316f,0f]