#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.temple_boss.bone.bone2] run function temple_boss:animations/animation.model.rotate/tree/bone2_root_top
execute if entity @s[tag=aj.temple_boss.bone.bone] run function temple_boss:animations/animation.model.rotate/tree/bone_root_top
execute store result entity @s Air short 1 run scoreboard players get .this aj.frame