#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[type=minecraft:area_effect_cloud] run function temple_boss:animations/animation.model.rotate/tree/root_bone_name
execute if entity @s[type=minecraft:armor_stand] run function temple_boss:animations/animation.model.rotate/tree/display_bone_name