#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.temple_boss.animation.model.idle.loopMode matches 0 run function temple_boss:animations/animation.model.idle/stop
execute if score @s aj.temple_boss.animation.model.idle.loopMode matches 1 run function temple_boss:animations/animation.model.idle/pause
execute if score @s aj.temple_boss.animation.model.idle.loopMode matches 2 run function temple_boss:animations/animation.model.idle/zzz/execute/50