#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run data modify entity @s Pose.Head set value [-18f,-82.5f,18f]
execute if score .this aj.frame matches 153 run data modify entity @s Pose.Head set value [18f,-82.5f,-18f]
execute if score .this aj.frame matches 154 run data modify entity @s Pose.Head set value [54f,-82.5f,-54f]
execute if score .this aj.frame matches 155 run data modify entity @s Pose.Head set value [90f,-82.5f,-90f]
execute if score .this aj.frame matches 156 run data modify entity @s Pose.Head set value [72f,-66f,-72f]
execute if score .this aj.frame matches 157 run data modify entity @s Pose.Head set value [54f,-49.5f,-54f]
execute if score .this aj.frame matches 158 run data modify entity @s Pose.Head set value [36f,-33f,-36f]
execute if score .this aj.frame matches 159 run data modify entity @s Pose.Head set value [18f,-16.5f,-18f]