#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.209 ^-0.297 ^0.744 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.227 ^-0.27 ^0.762 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.258 ^-0.258 ^0.79 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.227 ^-0.27 ^0.762 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.209 ^-0.297 ^0.744 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.209 ^-0.329 ^0.744 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.227 ^-0.356 ^0.762 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.258 ^-0.368 ^0.79 ~ ~