#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [0f,-45f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [0f,-67.5f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [0f,-90f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-15f,-88.75f,15f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-30f,-87.5f,30f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-45f,-86.25f,45f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-60f,-85f,60f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-75f,-83.75f,75f]