#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run tp @s ^0.625 ^-0.313 ^0.375 ~ ~
execute if score .this aj.frame matches 153 run tp @s ^0.625 ^-0.313 ^0.375 ~ ~
execute if score .this aj.frame matches 154 run tp @s ^0.625 ^-0.313 ^0.375 ~ ~
execute if score .this aj.frame matches 155 run tp @s ^0.625 ^-0.313 ^0.375 ~ ~
execute if score .this aj.frame matches 156 run tp @s ^0.5 ^-0.263 ^0.375 ~ ~
execute if score .this aj.frame matches 157 run tp @s ^0.375 ^-0.213 ^0.375 ~ ~
execute if score .this aj.frame matches 158 run tp @s ^0.25 ^-0.163 ^0.375 ~ ~
execute if score .this aj.frame matches 159 run tp @s ^0.125 ^-0.113 ^0.375 ~ ~