#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^0.218 ^0.403 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^0.505 ^0.422 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^0.796 ^0.43 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^1.088 ^0.426 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^1.381 ^0.411 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^1.143 ^0.422 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^0.903 ^0.434 ~ ~