#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.258 ^-0.258 ^0.79 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.227 ^-0.27 ^0.762 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.209 ^-0.297 ^0.744 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.209 ^-0.329 ^0.744 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.227 ^-0.356 ^0.762 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.258 ^-0.368 ^0.79 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.227 ^-0.356 ^0.762 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.209 ^-0.329 ^0.744 ~ ~