#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run data modify entity @s Pose.Head set value [-18f,-82.5f,18f]
execute if score .this aj.frame matches 129 run data modify entity @s Pose.Head set value [-54f,-82.5f,54f]
execute if score .this aj.frame matches 130 run data modify entity @s Pose.Head set value [-90f,-82.5f,90f]
execute if score .this aj.frame matches 131 run data modify entity @s Pose.Head set value [-54f,-82.5f,54f]
execute if score .this aj.frame matches 132 run data modify entity @s Pose.Head set value [-18f,-82.5f,18f]
execute if score .this aj.frame matches 133 run data modify entity @s Pose.Head set value [18f,-82.5f,-18f]
execute if score .this aj.frame matches 134 run data modify entity @s Pose.Head set value [54f,-82.5f,-54f]
execute if score .this aj.frame matches 135 run data modify entity @s Pose.Head set value [90f,-82.5f,-90f]