#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [0f,-3.75f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [0f,-5.625f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [0f,-7.5f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-0.3255f,-6.2925f,0.0391f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-1.2551f,-5.3333f,0.1403f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-2.6602f,-4.8413f,0.2861f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-4.3452f,-4.9809f,0.4727f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-6.0679f,-5.8437f,0.7057f]