#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run tp @s ^0.209 ^-0.297 ^0.744 ~ ~
execute if score .this aj.frame matches 153 run tp @s ^0.209 ^-0.329 ^0.744 ~ ~
execute if score .this aj.frame matches 154 run tp @s ^0.227 ^-0.356 ^0.762 ~ ~
execute if score .this aj.frame matches 155 run tp @s ^0.258 ^-0.368 ^0.79 ~ ~
execute if score .this aj.frame matches 156 run tp @s ^0.203 ^-0.406 ^0.696 ~ ~
execute if score .this aj.frame matches 157 run tp @s ^0.117 ^-0.365 ^0.562 ~ ~
execute if score .this aj.frame matches 158 run tp @s ^0.046 ^-0.262 ^0.454 ~ ~
execute if score .this aj.frame matches 159 run tp @s ^0.01 ^-0.145 ^0.393 ~ ~