#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [-7.564f,-7.4355f,0.9845f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [-6.0703f,-3.0579f,0.5594f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [-2.3117f,-0.3629f,0.1588f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [2.3117f,-0.3629f,-0.1588f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [6.0703f,-3.0579f,-0.5594f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [7.564f,-7.4355f,-0.9845f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [6.0703f,-3.0579f,-0.5594f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [2.3117f,-0.3629f,-0.1588f]