#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^0.209 ^-0.297 ^0.744 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^0.227 ^-0.27 ^0.762 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^0.258 ^-0.258 ^0.79 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^0.227 ^-0.27 ^0.762 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^0.209 ^-0.297 ^0.744 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^0.209 ^-0.329 ^0.744 ~ ~
execute if score .this aj.frame matches 134 run tp @s ^0.227 ^-0.356 ^0.762 ~ ~
execute if score .this aj.frame matches 135 run tp @s ^0.258 ^-0.368 ^0.79 ~ ~