#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.227 ^-0.356 ^0.762 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.209 ^-0.329 ^0.744 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.209 ^-0.297 ^0.744 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.227 ^-0.27 ^0.762 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.258 ^-0.258 ^0.79 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.227 ^-0.27 ^0.762 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.209 ^-0.297 ^0.744 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.209 ^-0.329 ^0.744 ~ ~