#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run data modify entity @s Pose.Head set value [6.0703f,-3.0579f,-0.5594f]
execute if score .this aj.frame matches 137 run data modify entity @s Pose.Head set value [2.3117f,-0.3629f,-0.1588f]
execute if score .this aj.frame matches 138 run data modify entity @s Pose.Head set value [-2.3117f,-0.3629f,0.1588f]
execute if score .this aj.frame matches 139 run data modify entity @s Pose.Head set value [-6.0703f,-3.0579f,0.5594f]
execute if score .this aj.frame matches 140 run data modify entity @s Pose.Head set value [-7.564f,-7.4355f,0.9845f]
execute if score .this aj.frame matches 141 run data modify entity @s Pose.Head set value [-6.0703f,-3.0579f,0.5594f]
execute if score .this aj.frame matches 142 run data modify entity @s Pose.Head set value [-2.3117f,-0.3629f,0.1588f]
execute if score .this aj.frame matches 143 run data modify entity @s Pose.Head set value [2.3117f,-0.3629f,-0.1588f]