#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.178 ^0.147 ^0.454 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^0.203 ^0.469 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.178 ^0.147 ^0.454 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.019 ^0.207 ^0.468 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.211 ^0.133 ^0.444 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.009 ^0.21 ^0.467 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.195 ^0.14 ^0.449 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.028 ^0.2 ^0.47 ~ ~