#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [-90f,-82.5f,90f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [-54f,-82.5f,54f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [-18f,-82.5f,18f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [18f,-82.5f,-18f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [54f,-82.5f,-54f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [90f,-82.5f,-90f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [54f,-82.5f,-54f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [18f,-82.5f,-18f]