#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run tp @s ^0.227 ^-0.356 ^0.762 ~ ~
execute if score .this aj.frame matches 137 run tp @s ^0.209 ^-0.329 ^0.744 ~ ~
execute if score .this aj.frame matches 138 run tp @s ^0.209 ^-0.297 ^0.744 ~ ~
execute if score .this aj.frame matches 139 run tp @s ^0.227 ^-0.27 ^0.762 ~ ~
execute if score .this aj.frame matches 140 run tp @s ^0.258 ^-0.258 ^0.79 ~ ~
execute if score .this aj.frame matches 141 run tp @s ^0.227 ^-0.27 ^0.762 ~ ~
execute if score .this aj.frame matches 142 run tp @s ^0.209 ^-0.297 ^0.744 ~ ~
execute if score .this aj.frame matches 143 run tp @s ^0.209 ^-0.329 ^0.744 ~ ~