#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [-90f,-82.5f,90f]
execute if score .this aj.frame matches 121 run data modify entity @s Pose.Head set value [-54f,-82.5f,54f]
execute if score .this aj.frame matches 122 run data modify entity @s Pose.Head set value [-18f,-82.5f,18f]
execute if score .this aj.frame matches 123 run data modify entity @s Pose.Head set value [18f,-82.5f,-18f]
execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [54f,-82.5f,-54f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [90f,-82.5f,-90f]
execute if score .this aj.frame matches 126 run data modify entity @s Pose.Head set value [54f,-82.5f,-54f]
execute if score .this aj.frame matches 127 run data modify entity @s Pose.Head set value [18f,-82.5f,-18f]