#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.042 ^-0.313 ^0.498 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.12 ^-0.313 ^0.633 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.258 ^-0.313 ^0.793 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.249 ^-0.311 ^0.785 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.243 ^-0.304 ^0.779 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.239 ^-0.294 ^0.775 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.24 ^-0.282 ^0.776 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.247 ^-0.27 ^0.78 ~ ~