#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^0.203 ^0.031 ^0.379 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^0.203 ^0.028 ^0.42 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^0.203 ^0.031 ^0.379 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^0.206 ^0.032 ^0.336 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^0.207 ^0.029 ^0.309 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^0.206 ^0.027 ^0.306 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^0.203 ^0.028 ^0.33 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^0.206 ^0.027 ^0.306 ~ ~