#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [-2.3117f,-0.3629f,0.1588f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [2.3117f,-0.3629f,-0.1588f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [6.0703f,-3.0579f,-0.5594f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [7.564f,-7.4355f,-0.9845f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [6.0703f,-3.0579f,-0.5594f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [2.3117f,-0.3629f,-0.1588f]
execute if score .this aj.frame matches 118 run data modify entity @s Pose.Head set value [-2.3117f,-0.3629f,0.1588f]
execute if score .this aj.frame matches 119 run data modify entity @s Pose.Head set value [-6.0703f,-3.0579f,0.5594f]