#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.014 ^0.031 ^0.077 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.079 ^0.031 ^0.214 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.203 ^0.031 ^0.375 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.203 ^0.031 ^0.364 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.204 ^0.03 ^0.352 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.204 ^0.03 ^0.34 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.204 ^0.029 ^0.331 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.204 ^0.028 ^0.327 ~ ~