#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.203 ^0.031 ^0.379 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.203 ^0.028 ^0.42 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.203 ^0.031 ^0.379 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.206 ^0.032 ^0.336 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.207 ^0.029 ^0.309 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.206 ^0.027 ^0.306 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.203 ^0.028 ^0.33 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.206 ^0.027 ^0.306 ~ ~