#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [-2.3117f,-0.3629f,0.1588f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [2.3117f,-0.3629f,-0.1588f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [6.0703f,-3.0579f,-0.5594f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [7.564f,-7.4355f,-0.9845f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [6.0703f,-3.0579f,-0.5594f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [2.3117f,-0.3629f,-0.1588f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [-2.3117f,-0.3629f,0.1588f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [-6.0703f,-3.0579f,0.5594f]