#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^0.281 ^-0.047 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^0.492 ^-0.067 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^0.702 ^-0.086 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^0.911 ^-0.102 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^1.118 ^-0.117 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^1.325 ^-0.131 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^1.068 ^-0.117 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^0.811 ^-0.102 ~ ~