#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run tp @s ^0.203 ^0.031 ^0.379 ~ ~
execute if score .this aj.frame matches 145 run tp @s ^0.203 ^0.028 ^0.42 ~ ~
execute if score .this aj.frame matches 146 run tp @s ^0.203 ^0.031 ^0.379 ~ ~
execute if score .this aj.frame matches 147 run tp @s ^0.206 ^0.032 ^0.336 ~ ~
execute if score .this aj.frame matches 148 run tp @s ^0.207 ^0.029 ^0.309 ~ ~
execute if score .this aj.frame matches 149 run tp @s ^0.206 ^0.027 ^0.306 ~ ~
execute if score .this aj.frame matches 150 run tp @s ^0.203 ^0.028 ^0.33 ~ ~
execute if score .this aj.frame matches 151 run tp @s ^0.206 ^0.027 ^0.306 ~ ~