#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run tp @s ^0.207 ^0.029 ^0.309 ~ ~
execute if score .this aj.frame matches 153 run tp @s ^0.206 ^0.032 ^0.336 ~ ~
execute if score .this aj.frame matches 154 run tp @s ^0.203 ^0.031 ^0.379 ~ ~
execute if score .this aj.frame matches 155 run tp @s ^0.203 ^0.028 ^0.42 ~ ~
execute if score .this aj.frame matches 156 run tp @s ^0.073 ^0.065 ^0.455 ~ ~
execute if score .this aj.frame matches 157 run tp @s ^-0.051 ^0.125 ^0.395 ~ ~
execute if score .this aj.frame matches 158 run tp @s ^-0.121 ^0.218 ^0.258 ~ ~
execute if score .this aj.frame matches 159 run tp @s ^-0.096 ^0.296 ^0.092 ~ ~