#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [6.0703f,-3.0579f,-0.5594f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [7.564f,-7.4355f,-0.9845f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [6.0703f,-3.0579f,-0.5594f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [2.3117f,-0.3629f,-0.1588f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [-2.3117f,-0.3629f,0.1588f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [-6.0703f,-3.0579f,0.5594f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [-7.564f,-7.4355f,0.9845f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [-6.0703f,-3.0579f,0.5594f]