#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^0.207 ^0.029 ^0.309 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^0.206 ^0.027 ^0.306 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^0.203 ^0.028 ^0.33 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^0.206 ^0.027 ^0.306 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^0.207 ^0.029 ^0.309 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^0.206 ^0.032 ^0.336 ~ ~
execute if score .this aj.frame matches 134 run tp @s ^0.203 ^0.031 ^0.379 ~ ~
execute if score .this aj.frame matches 135 run tp @s ^0.203 ^0.028 ^0.42 ~ ~