#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.203 ^0.028 ^0.33 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.206 ^0.027 ^0.306 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.207 ^0.029 ^0.309 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.206 ^0.032 ^0.336 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.203 ^0.031 ^0.379 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.203 ^0.028 ^0.42 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.203 ^0.031 ^0.379 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.206 ^0.032 ^0.336 ~ ~