#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-51f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-53f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-55f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-57.218f,8.9749f,-13.7791f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-59.4361f,17.9497f,-27.5581f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-57.6818f,4.7062f,-7.5893f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-55.9276f,-8.5373f,12.3796f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-56.7641f,2.7456f,-4.263f]