#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run tp @s ^0.203 ^0.031 ^0.379 ~ ~
execute if score .this aj.frame matches 137 run tp @s ^0.206 ^0.032 ^0.336 ~ ~
execute if score .this aj.frame matches 138 run tp @s ^0.207 ^0.029 ^0.309 ~ ~
execute if score .this aj.frame matches 139 run tp @s ^0.206 ^0.027 ^0.306 ~ ~
execute if score .this aj.frame matches 140 run tp @s ^0.203 ^0.028 ^0.33 ~ ~
execute if score .this aj.frame matches 141 run tp @s ^0.206 ^0.027 ^0.306 ~ ~
execute if score .this aj.frame matches 142 run tp @s ^0.207 ^0.029 ^0.309 ~ ~
execute if score .this aj.frame matches 143 run tp @s ^0.206 ^0.032 ^0.336 ~ ~