#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run data modify entity @s Pose.Head set value [6.0703f,-3.0579f,-0.5594f]
execute if score .this aj.frame matches 145 run data modify entity @s Pose.Head set value [7.564f,-7.4355f,-0.9845f]
execute if score .this aj.frame matches 146 run data modify entity @s Pose.Head set value [6.0703f,-3.0579f,-0.5594f]
execute if score .this aj.frame matches 147 run data modify entity @s Pose.Head set value [2.3117f,-0.3629f,-0.1588f]
execute if score .this aj.frame matches 148 run data modify entity @s Pose.Head set value [-2.3117f,-0.3629f,0.1588f]
execute if score .this aj.frame matches 149 run data modify entity @s Pose.Head set value [-6.0703f,-3.0579f,0.5594f]
execute if score .this aj.frame matches 150 run data modify entity @s Pose.Head set value [-7.564f,-7.4355f,0.9845f]
execute if score .this aj.frame matches 151 run data modify entity @s Pose.Head set value [-6.0703f,-3.0579f,0.5594f]