#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^0.207 ^0.029 ^0.309 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^0.206 ^0.032 ^0.336 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^0.203 ^0.031 ^0.379 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^0.203 ^0.028 ^0.42 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^0.203 ^0.031 ^0.379 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^0.206 ^0.032 ^0.336 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^0.207 ^0.029 ^0.309 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^0.206 ^0.027 ^0.306 ~ ~