#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-2.3117f,-0.3629f,0.1588f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-6.0703f,-3.0579f,0.5594f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-7.564f,-7.4355f,0.9845f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-6.0703f,-3.0579f,0.5594f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-2.3117f,-0.3629f,0.1588f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [2.3117f,-0.3629f,-0.1588f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [6.0703f,-3.0579f,-0.5594f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [7.564f,-7.4355f,-0.9845f]