#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.103 ^-0.715 ^0.05 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.073 ^-0.71 ^-0.015 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.052 ^-0.686 ^-0.073 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.05 ^-0.652 ^-0.102 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.071 ^-0.624 ^-0.09 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.103 ^-0.617 ^-0.043 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.071 ^-0.624 ^-0.09 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.05 ^-0.652 ^-0.102 ~ ~