#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128..135 run function temple_boss:animations/animation.model.attack_3/tree/left_leg_display_128-135
execute if score .this aj.frame matches 136..143 run function temple_boss:animations/animation.model.attack_3/tree/left_leg_display_136-143
execute if score .this aj.frame matches 144..151 run function temple_boss:animations/animation.model.attack_3/tree/left_leg_display_144-151
execute if score .this aj.frame matches 152..159 run function temple_boss:animations/animation.model.attack_3/tree/left_leg_display_152-159
execute if score .this aj.frame matches 160 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]
execute if score .this aj.frame matches 161 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]