#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128..135 run function temple_boss:animations/animation.model.attack_3/tree/left_leg_root_128-135
execute if score .this aj.frame matches 136..143 run function temple_boss:animations/animation.model.attack_3/tree/left_leg_root_136-143
execute if score .this aj.frame matches 144..151 run function temple_boss:animations/animation.model.attack_3/tree/left_leg_root_144-151
execute if score .this aj.frame matches 152..159 run function temple_boss:animations/animation.model.attack_3/tree/left_leg_root_152-159
execute if score .this aj.frame matches 160 run tp @s ^0.219 ^-1.063 ^-0.344 ~ ~
execute if score .this aj.frame matches 161 run tp @s ^0.219 ^-1.063 ^-0.344 ~ ~