#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run data modify entity @s Pose.Head set value [152.2345f,-74.315f,168.2824f]
execute if score .this aj.frame matches 129 run data modify entity @s Pose.Head set value [161.6833f,-70.6557f,159.5536f]
execute if score .this aj.frame matches 130 run data modify entity @s Pose.Head set value [161.2265f,-66.0354f,160.2668f]
execute if score .this aj.frame matches 131 run data modify entity @s Pose.Head set value [161.6833f,-70.6557f,159.5536f]
execute if score .this aj.frame matches 132 run data modify entity @s Pose.Head set value [152.2345f,-74.315f,168.2824f]
execute if score .this aj.frame matches 133 run data modify entity @s Pose.Head set value [134.9508f,-74.603f,-175.3451f]
execute if score .this aj.frame matches 134 run data modify entity @s Pose.Head set value [123.9458f,-71.275f,-165.1056f]
execute if score .this aj.frame matches 135 run data modify entity @s Pose.Head set value [123.2851f,-66.6577f,-164.7767f]