#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run tp @s ^-0.071 ^-0.624 ^-0.09 ~ ~
execute if score .this aj.frame matches 137 run tp @s ^-0.05 ^-0.652 ^-0.102 ~ ~
execute if score .this aj.frame matches 138 run tp @s ^-0.052 ^-0.686 ^-0.073 ~ ~
execute if score .this aj.frame matches 139 run tp @s ^-0.073 ^-0.71 ^-0.015 ~ ~
execute if score .this aj.frame matches 140 run tp @s ^-0.103 ^-0.715 ^0.05 ~ ~
execute if score .this aj.frame matches 141 run tp @s ^-0.073 ^-0.71 ^-0.015 ~ ~
execute if score .this aj.frame matches 142 run tp @s ^-0.052 ^-0.686 ^-0.073 ~ ~
execute if score .this aj.frame matches 143 run tp @s ^-0.05 ^-0.652 ^-0.102 ~ ~