#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.041 ^-1.313 ^-0.288 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.112 ^-1.313 ^-0.102 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.094 ^-1.313 ^0.156 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.089 ^-1.314 ^0.147 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.085 ^-1.318 ^0.151 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.084 ^-1.323 ^0.17 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.085 ^-1.328 ^0.201 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.089 ^-1.332 ^0.242 ~ ~