#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-18.5813f,-14.557f,-46.2245f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-20.0205f,-17.9095f,-56.7812f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-20.1769f,-21.7708f,-67.6059f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-18.8351f,-25.7789f,-78.9032f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-15.8322f,-29.5155f,-90.8919f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-15.8928f,-26.0159f,-90.8637f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-15.9499f,-22.5163f,-90.8402f]