#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-90.7935f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-90.7935f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-90.7935f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-90.7935f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-90.7935f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-90.7935f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-90.7935f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [6.8189f,-10.788f,-95.3852f]