#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run tp @s ^-0.071 ^-1.281 ^-0.003 ~ ~
execute if score .this aj.frame matches 145 run tp @s ^-0.094 ^-1.276 ^0.028 ~ ~
execute if score .this aj.frame matches 146 run tp @s ^-0.071 ^-1.281 ^-0.003 ~ ~
execute if score .this aj.frame matches 147 run tp @s ^-0.059 ^-1.302 ^0.029 ~ ~
execute if score .this aj.frame matches 148 run tp @s ^-0.064 ^-1.323 ^0.109 ~ ~
execute if score .this aj.frame matches 149 run tp @s ^-0.079 ^-1.333 ^0.209 ~ ~
execute if score .this aj.frame matches 150 run tp @s ^-0.094 ^-1.333 ^0.289 ~ ~
execute if score .this aj.frame matches 151 run tp @s ^-0.079 ^-1.333 ^0.209 ~ ~