#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [67.0123f,10.6419f,-102.883f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [63.3967f,13.6225f,-104.109f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [62.665f,16.3511f,-104.9413f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [64.4504f,20.6536f,-104.8399f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [67.4986f,27.6197f,-103.5908f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [64.4504f,20.6536f,-104.8399f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [62.665f,16.3511f,-104.9413f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [63.3967f,13.6225f,-104.109f]