#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [29.4413f,-7.9117f,-99.1089f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [51.6952f,-3.8511f,-101.4195f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [73.7283f,0.7762f,-102.0185f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [71.3891f,5.9105f,-102.2166f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [69.3791f,10.4943f,-102.6683f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [67.8817f,14.7009f,-103.2191f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [67.0351f,18.7736f,-103.6828f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [66.9085f,22.9903f,-103.8668f]