#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [37.2333f,-22.1749f,3.9109f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [41.0097f,-22.3701f,2.4792f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [44.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [38.7229f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [32.6515f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [26.58f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [20.5086f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [14.4372f,-22.4774f,1.0351f]