#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [62.665f,16.3511f,-104.9413f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [63.3967f,13.6225f,-104.109f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [67.0123f,10.6419f,-102.883f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [72.6833f,5.6662f,-102.0773f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [67.0123f,10.6419f,-102.883f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [63.3967f,13.6225f,-104.109f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [62.665f,16.3511f,-104.9413f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [64.4504f,20.6536f,-104.8399f]