#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.071 ^-1.281 ^-0.003 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.094 ^-1.276 ^0.028 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.071 ^-1.281 ^-0.003 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.059 ^-1.302 ^0.029 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.064 ^-1.323 ^0.109 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.079 ^-1.333 ^0.209 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.094 ^-1.333 ^0.289 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.079 ^-1.333 ^0.209 ~ ~