#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.071 ^-0.624 ^-0.09 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.103 ^-0.617 ^-0.043 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.071 ^-0.624 ^-0.09 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.05 ^-0.652 ^-0.102 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.052 ^-0.686 ^-0.073 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.073 ^-0.71 ^-0.015 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.103 ^-0.715 ^0.05 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.073 ^-0.71 ^-0.015 ~ ~