#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run tp @s ^-0.071 ^-1.281 ^-0.003 ~ ~
execute if score .this aj.frame matches 137 run tp @s ^-0.059 ^-1.302 ^0.029 ~ ~
execute if score .this aj.frame matches 138 run tp @s ^-0.064 ^-1.323 ^0.109 ~ ~
execute if score .this aj.frame matches 139 run tp @s ^-0.079 ^-1.333 ^0.209 ~ ~
execute if score .this aj.frame matches 140 run tp @s ^-0.094 ^-1.333 ^0.289 ~ ~
execute if score .this aj.frame matches 141 run tp @s ^-0.079 ^-1.333 ^0.209 ~ ~
execute if score .this aj.frame matches 142 run tp @s ^-0.064 ^-1.323 ^0.109 ~ ~
execute if score .this aj.frame matches 143 run tp @s ^-0.059 ^-1.302 ^0.029 ~ ~