#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^-0.071 ^-1.281 ^-0.003 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^-0.094 ^-1.276 ^0.028 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^-0.071 ^-1.281 ^-0.003 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^-0.059 ^-1.302 ^0.029 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^-0.064 ^-1.323 ^0.109 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^-0.079 ^-1.333 ^0.209 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^-0.094 ^-1.333 ^0.289 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^-0.079 ^-1.333 ^0.209 ~ ~