#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^-0.103 ^-0.715 ^0.05 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^-0.073 ^-0.71 ^-0.015 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^-0.052 ^-0.686 ^-0.073 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^-0.05 ^-0.652 ^-0.102 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^-0.071 ^-0.624 ^-0.09 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^-0.103 ^-0.617 ^-0.043 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^-0.071 ^-0.624 ^-0.09 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^-0.05 ^-0.652 ^-0.102 ~ ~