#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.094 ^-1.333 ^0.289 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.079 ^-1.333 ^0.209 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.064 ^-1.323 ^0.109 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.059 ^-1.302 ^0.029 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.071 ^-1.281 ^-0.003 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.094 ^-1.276 ^0.028 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^-0.071 ^-1.281 ^-0.003 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^-0.059 ^-1.302 ^0.029 ~ ~