#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.118 ^-1.201 ^-0.131 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.09 ^-1.195 ^-0.032 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.057 ^-1.169 ^0.052 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.09 ^-1.195 ^-0.032 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.118 ^-1.201 ^-0.131 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.125 ^-1.194 ^-0.218 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.101 ^-1.192 ^-0.264 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.057 ^-1.215 ^-0.254 ~ ~