#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^0.101 ^-1.192 ^-0.264 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^0.125 ^-1.194 ^-0.218 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^0.118 ^-1.201 ^-0.131 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^0.09 ^-1.195 ^-0.032 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^0.057 ^-1.169 ^0.052 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^0.09 ^-1.195 ^-0.032 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^0.118 ^-1.201 ^-0.131 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^0.125 ^-1.194 ^-0.218 ~ ~