#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run tp @s ^-0.089 ^-1.267 ^0.865 ~ ~
execute if score .this aj.frame matches 153 run tp @s ^-0.084 ^-1.274 ^0.783 ~ ~
execute if score .this aj.frame matches 154 run tp @s ^-0.06 ^-1.27 ^0.748 ~ ~
execute if score .this aj.frame matches 155 run tp @s ^-0.025 ^-1.251 ^0.768 ~ ~
execute if score .this aj.frame matches 156 run tp @s ^-0.187 ^-1.337 ^0.41 ~ ~
execute if score .this aj.frame matches 157 run tp @s ^-0.306 ^-1.298 ^-0.014 ~ ~
execute if score .this aj.frame matches 158 run tp @s ^-0.311 ^-1.22 ^-0.34 ~ ~
execute if score .this aj.frame matches 159 run tp @s ^-0.282 ^-1.228 ^-0.438 ~ ~