#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.412 ^-1.276 ^-0.193 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.449 ^-1.031 ^-0.12 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.478 ^-0.774 ^-0.052 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.497 ^-0.51 ^0.012 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.506 ^-0.239 ^0.071 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.505 ^0.034 ^0.123 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.505 ^-0.236 ^0.057 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.505 ^-0.502 ^-0.008 ~ ~