#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run tp @s ^-0.06 ^-1.27 ^0.748 ~ ~
execute if score .this aj.frame matches 145 run tp @s ^-0.025 ^-1.251 ^0.768 ~ ~
execute if score .this aj.frame matches 146 run tp @s ^-0.06 ^-1.27 ^0.748 ~ ~
execute if score .this aj.frame matches 147 run tp @s ^-0.084 ^-1.274 ^0.783 ~ ~
execute if score .this aj.frame matches 148 run tp @s ^-0.089 ^-1.267 ^0.865 ~ ~
execute if score .this aj.frame matches 149 run tp @s ^-0.068 ^-1.262 ^0.964 ~ ~
execute if score .this aj.frame matches 150 run tp @s ^-0.025 ^-1.276 ^1.04 ~ ~
execute if score .this aj.frame matches 151 run tp @s ^-0.068 ^-1.262 ^0.964 ~ ~