#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^0.118 ^-1.201 ^-0.131 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^0.09 ^-1.195 ^-0.032 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^0.057 ^-1.169 ^0.052 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^0.09 ^-1.195 ^-0.032 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^0.118 ^-1.201 ^-0.131 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^0.125 ^-1.194 ^-0.218 ~ ~
execute if score .this aj.frame matches 134 run tp @s ^0.101 ^-1.192 ^-0.264 ~ ~
execute if score .this aj.frame matches 135 run tp @s ^0.057 ^-1.215 ^-0.254 ~ ~