#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [9.9917f,14.7693f,-4.2121f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [9.9917f,14.7693f,-4.2121f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [9.9917f,14.7693f,-4.2121f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [9.9917f,14.7693f,-4.2121f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [9.9917f,14.7693f,-4.2121f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [9.9917f,14.7693f,-4.2121f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [9.9917f,14.7693f,-4.2121f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [11.6169f,-7.6729f,-4.1095f]