#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [19.7095f,-85.3254f,-19.5364f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-13.1155f,-82.677f,13.3648f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-39.0727f,-80.7989f,39.2911f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-64.0056f,-79.9184f,64.1214f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-90f,-80f,90f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-64.0056f,-79.9184f,64.1214f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-39.0727f,-80.7989f,39.2911f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-13.1155f,-82.677f,13.3648f]