#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [13.4336f,-30.1083f,-4.7092f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [16.3921f,-52.503f,-6.7002f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [26.1054f,-74.6547f,-15.5676f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [26.9494f,-72.3926f,-14.9429f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [26.405f,-70.6483f,-12.9305f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [25.1565f,-69.5751f,-10.2033f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [23.6699f,-69.2726f,-7.1965f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [22.3474f,-69.7918f,-4.2694f]