#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-6.9934f,0.3046f,2.4814f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-3.4967f,0.1526f,2.4953f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [0f,0f,2.5f]