#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^0.057 ^-1.169 ^0.052 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^0.09 ^-1.195 ^-0.032 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^0.118 ^-1.201 ^-0.131 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^0.125 ^-1.194 ^-0.218 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^0.101 ^-1.192 ^-0.264 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^0.057 ^-1.215 ^-0.254 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^0.101 ^-1.192 ^-0.264 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^0.125 ^-1.194 ^-0.218 ~ ~