#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.505 ^-0.764 ^-0.071 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.505 ^-1.022 ^-0.133 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.505 ^-1.277 ^-0.193 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.505 ^-1.277 ^-0.193 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.505 ^-1.277 ^-0.193 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.505 ^-1.277 ^-0.193 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.505 ^-1.277 ^-0.193 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.505 ^-1.277 ^-0.193 ~ ~