#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.101 ^-1.192 ^-0.264 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.057 ^-1.215 ^-0.254 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.101 ^-1.192 ^-0.264 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.125 ^-1.194 ^-0.218 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.118 ^-1.201 ^-0.131 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.09 ^-1.195 ^-0.032 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.057 ^-1.169 ^0.052 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.09 ^-1.195 ^-0.032 ~ ~