#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^-0.06 ^-1.27 ^0.748 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^-0.084 ^-1.274 ^0.783 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^-0.089 ^-1.267 ^0.865 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^-0.068 ^-1.262 ^0.964 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^-0.025 ^-1.276 ^1.04 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^-0.068 ^-1.262 ^0.964 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^-0.089 ^-1.267 ^0.865 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^-0.084 ^-1.274 ^0.783 ~ ~