#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.412 ^-1.315 ^-0.275 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.449 ^-1.082 ^-0.199 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.481 ^-0.838 ^-0.126 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.506 ^-0.587 ^-0.057 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.524 ^-0.328 ^0.008 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.534 ^-0.064 ^0.068 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.534 ^-0.331 ^-0.004 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.534 ^-0.593 ^-0.074 ~ ~