#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.025 ^-1.276 ^1.04 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.068 ^-1.262 ^0.964 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.089 ^-1.267 ^0.865 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.084 ^-1.274 ^0.783 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.06 ^-1.27 ^0.748 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.025 ^-1.251 ^0.768 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^-0.06 ^-1.27 ^0.748 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^-0.084 ^-1.274 ^0.783 ~ ~