#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [23.4654f,-64.809f,-7.7583f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [29.6286f,-64.948f,-15.3245f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [36.5209f,-67.6804f,-23.6333f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [42.4556f,-72.6477f,-31.2674f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [36.5209f,-67.6804f,-23.6333f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [29.6286f,-64.948f,-15.3245f]
execute if score .this aj.frame matches 118 run data modify entity @s Pose.Head set value [23.4654f,-64.809f,-7.7583f]
execute if score .this aj.frame matches 119 run data modify entity @s Pose.Head set value [19.8085f,-67.1282f,-2.3487f]