#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.268 ^-1.277 ^-0.383 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.137 ^-1.277 ^-0.308 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.057 ^-1.277 ^-0.13 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.068 ^-1.251 ^-0.131 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.076 ^-1.231 ^-0.118 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.079 ^-1.215 ^-0.09 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.077 ^-1.2 ^-0.05 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.069 ^-1.186 ^-0.002 ~ ~