#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-2.4976f,-44.9455f,3.5333f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-6.0115f,-67.3687f,6.5088f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-90f,-87.5f,90f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-66.8363f,-86.9293f,66.8626f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-59.9764f,-85.6702f,60.0236f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-62.7331f,-84.2064f,62.791f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-69.8655f,-82.727f,69.9202f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-79.2504f,-81.3112f,79.2858f]