#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run data modify entity @s Pose.Head set value [-39.0727f,-80.7989f,39.2911f]
execute if score .this aj.frame matches 153 run data modify entity @s Pose.Head set value [-13.1155f,-82.677f,13.3648f]
execute if score .this aj.frame matches 154 run data modify entity @s Pose.Head set value [19.7095f,-85.3254f,-19.5364f]
execute if score .this aj.frame matches 155 run data modify entity @s Pose.Head set value [90f,-87.5f,-90f]
execute if score .this aj.frame matches 156 run data modify entity @s Pose.Head set value [69.1689f,-69.3021f,-68.9404f]
execute if score .this aj.frame matches 157 run data modify entity @s Pose.Head set value [52.5594f,-51.1033f,-52.1279f]
execute if score .this aj.frame matches 158 run data modify entity @s Pose.Head set value [35.7354f,-33.293f,-35.5161f]
execute if score .this aj.frame matches 159 run data modify entity @s Pose.Head set value [18.2787f,-16.1887f,-18.9903f]