#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^-0.145 ^-0.655 ^0.671 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^-0.143 ^-0.682 ^0.642 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^-0.128 ^-0.704 ^0.653 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^-0.103 ^-0.715 ^0.7 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^-0.128 ^-0.704 ^0.653 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^-0.143 ^-0.682 ^0.642 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^-0.145 ^-0.655 ^0.671 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^-0.131 ^-0.63 ^0.729 ~ ~