#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run tp @s ^-0.128 ^-0.704 ^0.653 ~ ~
execute if score .this aj.frame matches 137 run tp @s ^-0.143 ^-0.682 ^0.642 ~ ~
execute if score .this aj.frame matches 138 run tp @s ^-0.145 ^-0.655 ^0.671 ~ ~
execute if score .this aj.frame matches 139 run tp @s ^-0.131 ^-0.63 ^0.729 ~ ~
execute if score .this aj.frame matches 140 run tp @s ^-0.103 ^-0.617 ^0.793 ~ ~
execute if score .this aj.frame matches 141 run tp @s ^-0.131 ^-0.63 ^0.729 ~ ~
execute if score .this aj.frame matches 142 run tp @s ^-0.145 ^-0.655 ^0.671 ~ ~
execute if score .this aj.frame matches 143 run tp @s ^-0.143 ^-0.682 ^0.642 ~ ~