#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run tp @s ^-0.104 ^-1.328 ^0.431 ~ ~
execute if score .this aj.frame matches 137 run tp @s ^-0.113 ^-1.319 ^0.462 ~ ~
execute if score .this aj.frame matches 138 run tp @s ^-0.118 ^-1.305 ^0.543 ~ ~
execute if score .this aj.frame matches 139 run tp @s ^-0.112 ^-1.287 ^0.642 ~ ~
execute if score .this aj.frame matches 140 run tp @s ^-0.094 ^-1.276 ^0.722 ~ ~
execute if score .this aj.frame matches 141 run tp @s ^-0.112 ^-1.287 ^0.642 ~ ~
execute if score .this aj.frame matches 142 run tp @s ^-0.118 ^-1.305 ^0.543 ~ ~
execute if score .this aj.frame matches 143 run tp @s ^-0.113 ^-1.319 ^0.462 ~ ~