#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^-0.104 ^-1.328 ^0.431 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^-0.113 ^-1.319 ^0.462 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^-0.118 ^-1.305 ^0.543 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^-0.112 ^-1.287 ^0.642 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^-0.094 ^-1.276 ^0.722 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^-0.112 ^-1.287 ^0.642 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^-0.118 ^-1.305 ^0.543 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^-0.113 ^-1.319 ^0.462 ~ ~