#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^-0.104 ^-1.328 ^0.431 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^-0.094 ^-1.333 ^0.461 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^-0.104 ^-1.328 ^0.431 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^-0.113 ^-1.319 ^0.462 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^-0.118 ^-1.305 ^0.543 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^-0.112 ^-1.287 ^0.642 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^-0.094 ^-1.276 ^0.722 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^-0.112 ^-1.287 ^0.642 ~ ~