#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [18.1908f,-13.7521f,7.1769f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [14.771f,-10.5581f,8.1858f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [10.128f,-9.855f,9.2973f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [5.9026f,-11.8943f,10.3833f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [3.6081f,-15.9461f,11.2241f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [5.9026f,-11.8943f,10.3833f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [10.128f,-9.855f,9.2973f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [14.771f,-10.5581f,8.1858f]