#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [-82.8186f,6.7766f,90.7066f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [-82.7967f,8.1067f,91.1663f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [-85.5264f,10.3893f,91.0421f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [-90f,15f,90f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [-85.5264f,10.3893f,91.0421f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [-82.7967f,8.1067f,91.1663f]
execute if score .this aj.frame matches 118 run data modify entity @s Pose.Head set value [-82.8186f,6.7766f,90.7066f]
execute if score .this aj.frame matches 119 run data modify entity @s Pose.Head set value [-85.5858f,4.5661f,90.1183f]