#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [9.6429f,23.5714f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [3.75f,27.5f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-2.1429f,31.4286f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-8.0357f,35.3571f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-13.9286f,39.2857f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-19.8214f,43.2143f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-25.7143f,47.1429f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-31.6071f,51.0714f,0f]