#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [18.1908f,-13.7521f,7.1769f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [19.1162f,-18.2891f,6.6329f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [18.1908f,-13.7521f,7.1769f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [14.771f,-10.5581f,8.1858f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [10.128f,-9.855f,9.2973f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [5.9026f,-11.8943f,10.3833f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [3.6081f,-15.9461f,11.2241f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [5.9026f,-11.8943f,10.3833f]