#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-0.9182f,6.9398f,82.4443f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-0.4574f,3.47f,82.4861f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [0f,0f,82.5f]