#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.375 ^-0.225 ^-0.33 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.375 ^-0.03 ^-0.304 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.375 ^0.167 ^-0.276 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.375 ^0.365 ^-0.245 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.375 ^0.566 ^-0.212 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.375 ^0.315 ^-0.245 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.375 ^0.067 ^-0.276 ~ ~