#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [10.128f,-9.855f,9.2973f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [14.771f,-10.5581f,8.1858f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [18.1908f,-13.7521f,7.1769f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [19.1162f,-18.2891f,6.6329f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [18.1908f,-13.7521f,7.1769f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [14.771f,-10.5581f,8.1858f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [10.128f,-9.855f,9.2973f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [5.9026f,-11.8943f,10.3833f]