#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-85.5264f,10.3893f,91.0421f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-82.7967f,8.1067f,91.1663f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-82.8186f,6.7766f,90.7066f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-85.5858f,4.5661f,90.1183f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-90f,0f,90f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-85.5858f,4.5661f,90.1183f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-82.8186f,6.7766f,90.7066f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-82.7967f,8.1067f,91.1663f]