#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^-0.145 ^-0.655 ^0.671 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^-0.131 ^-0.63 ^0.729 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^-0.103 ^-0.617 ^0.793 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^-0.131 ^-0.63 ^0.729 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^-0.145 ^-0.655 ^0.671 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^-0.143 ^-0.682 ^0.642 ~ ~
execute if score .this aj.frame matches 134 run tp @s ^-0.128 ^-0.704 ^0.653 ~ ~
execute if score .this aj.frame matches 135 run tp @s ^-0.103 ^-0.715 ^0.7 ~ ~