#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^-0.103 ^-0.617 ^0.793 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^-0.131 ^-0.63 ^0.729 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^-0.145 ^-0.655 ^0.671 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^-0.143 ^-0.682 ^0.642 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^-0.128 ^-0.704 ^0.653 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^-0.103 ^-0.715 ^0.7 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^-0.128 ^-0.704 ^0.653 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^-0.143 ^-0.682 ^0.642 ~ ~