#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run data modify entity @s Pose.Head set value [-82.8186f,6.7766f,90.7066f]
execute if score .this aj.frame matches 153 run data modify entity @s Pose.Head set value [-82.7967f,8.1067f,91.1663f]
execute if score .this aj.frame matches 154 run data modify entity @s Pose.Head set value [-85.5264f,10.3893f,91.0421f]
execute if score .this aj.frame matches 155 run data modify entity @s Pose.Head set value [-90f,15f,90f]
execute if score .this aj.frame matches 156 run data modify entity @s Pose.Head set value [-82.5118f,-15.3241f,89.4781f]
execute if score .this aj.frame matches 157 run data modify entity @s Pose.Head set value [-60.8814f,-38.3287f,78.0234f]
execute if score .this aj.frame matches 158 run data modify entity @s Pose.Head set value [-24.8712f,-41.5948f,52.0703f]
execute if score .this aj.frame matches 159 run data modify entity @s Pose.Head set value [-2.8222f,-24.0768f,37.7331f]