#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-178.7452f,-26.9205f,-147.5672f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-178.7452f,-26.9205f,-147.5672f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-178.7452f,-26.9205f,-147.5672f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-178.7452f,-26.9205f,-147.5672f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-178.7452f,-26.9205f,-147.5672f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-178.7452f,-26.9205f,-147.5672f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-178.7452f,-26.9205f,-147.5672f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-166.7984f,-7.4868f,-151.1639f]