#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-135.6418f,49.6303f,-142.0993f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-133.8408f,45.1703f,-140.4842f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-129.0423f,42.1157f,-136.8819f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-122.9264f,41.3677f,-132.5194f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-117.1522f,43.1338f,-128.3464f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-122.9264f,41.3677f,-132.5194f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-129.0423f,42.1157f,-136.8819f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-133.8408f,45.1703f,-140.4842f]