#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^1.023 ^-0.811 ^0.574 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^1.023 ^-1.109 ^0.508 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^1.023 ^-1.403 ^0.442 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^1.052 ^-1.295 ^0.507 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^1.077 ^-1.18 ^0.562 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^1.097 ^-1.059 ^0.605 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^1.112 ^-0.934 ^0.636 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^1.122 ^-0.806 ^0.654 ~ ~