#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function temple_boss:animations/animation.model.attack_3/tree/spear_display_0-63
execute if score .this aj.frame matches 64..127 run function temple_boss:animations/animation.model.attack_3/tree/spear_display_64-127
execute if score .this aj.frame matches 128..161 run function temple_boss:animations/animation.model.attack_3/tree/spear_display_128-161