#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^0.524 ^0.108 ^-0.672 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^0.601 ^0.134 ^-0.666 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^0.648 ^0.201 ^-0.635 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^0.645 ^0.28 ^-0.59 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^0.597 ^0.342 ^-0.549 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^0.524 ^0.364 ^-0.527 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^0.597 ^0.342 ^-0.549 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^0.645 ^0.28 ^-0.59 ~ ~