#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run tp @s ^0.597 ^0.342 ^-0.549 ~ ~
execute if score .this aj.frame matches 137 run tp @s ^0.645 ^0.28 ^-0.59 ~ ~
execute if score .this aj.frame matches 138 run tp @s ^0.648 ^0.201 ^-0.635 ~ ~
execute if score .this aj.frame matches 139 run tp @s ^0.601 ^0.134 ^-0.666 ~ ~
execute if score .this aj.frame matches 140 run tp @s ^0.524 ^0.108 ^-0.672 ~ ~
execute if score .this aj.frame matches 141 run tp @s ^0.601 ^0.134 ^-0.666 ~ ~
execute if score .this aj.frame matches 142 run tp @s ^0.648 ^0.201 ^-0.635 ~ ~
execute if score .this aj.frame matches 143 run tp @s ^0.645 ^0.28 ^-0.59 ~ ~