#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.597 ^0.342 ^-0.549 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.645 ^0.28 ^-0.59 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.648 ^0.201 ^-0.635 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.601 ^0.134 ^-0.666 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.524 ^0.108 ^-0.672 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.601 ^0.134 ^-0.666 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.648 ^0.201 ^-0.635 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.645 ^0.28 ^-0.59 ~ ~