#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.597 ^0.342 ^-0.549 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.524 ^0.364 ^-0.527 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.597 ^0.342 ^-0.549 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.645 ^0.28 ^-0.59 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.648 ^0.201 ^-0.635 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.601 ^0.134 ^-0.666 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.524 ^0.108 ^-0.672 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.601 ^0.134 ^-0.666 ~ ~