#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [149.1614f,5.2109f,-121.5393f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [152.2736f,0.5404f,-123.7061f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [155.5678f,-4.002f,-126.1288f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [159.0809f,-8.3928f,-128.8315f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [162.8509f,-12.6041f,-131.8423f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [166.9171f,-16.6035f,-135.1916f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [171.3179f,-20.3528f,-138.9108f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [176.0882f,-23.8083f,-143.0288f]