#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [-129.0423f,42.1157f,-136.8819f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [-133.8408f,45.1703f,-140.4842f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [-135.6418f,49.6303f,-142.0993f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [-132.988f,53.9533f,-140.3007f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [-135.6418f,49.6303f,-142.0993f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [-133.8408f,45.1703f,-140.4842f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [-129.0423f,42.1157f,-136.8819f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [-122.9264f,41.3677f,-132.5194f]