#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^0.648 ^0.201 ^-0.635 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^0.601 ^0.134 ^-0.666 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^0.524 ^0.108 ^-0.672 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^0.601 ^0.134 ^-0.666 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^0.648 ^0.201 ^-0.635 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^0.645 ^0.28 ^-0.59 ~ ~
execute if score .this aj.frame matches 134 run tp @s ^0.597 ^0.342 ^-0.549 ~ ~
execute if score .this aj.frame matches 135 run tp @s ^0.524 ^0.364 ^-0.527 ~ ~