#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-129.0423f,42.1157f,-136.8819f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-122.9264f,41.3677f,-132.5194f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-117.1522f,43.1338f,-128.3464f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-122.9264f,41.3677f,-132.5194f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-129.0423f,42.1157f,-136.8819f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-133.8408f,45.1703f,-140.4842f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-135.6418f,49.6303f,-142.0993f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-132.988f,53.9533f,-140.3007f]