#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [135.4656f,28.497f,-111.5668f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [133.9535f,31.7436f,-112.3259f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [132.3318f,34.971f,-113.218f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [135.1049f,29.8721f,-114.0526f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [137.835f,24.8129f,-115.1204f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [140.5679f,19.8045f,-116.4049f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [143.3429f,14.859f,-117.9003f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [146.196f,9.9895f,-119.6089f]