#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run tp @s ^0.648 ^0.201 ^-0.635 ~ ~
execute if score .this aj.frame matches 153 run tp @s ^0.645 ^0.28 ^-0.59 ~ ~
execute if score .this aj.frame matches 154 run tp @s ^0.597 ^0.342 ^-0.549 ~ ~
execute if score .this aj.frame matches 155 run tp @s ^0.524 ^0.364 ^-0.527 ~ ~
execute if score .this aj.frame matches 156 run tp @s ^0.741 ^0.402 ^-0.479 ~ ~
execute if score .this aj.frame matches 157 run tp @s ^1.034 ^0.298 ^-0.409 ~ ~
execute if score .this aj.frame matches 158 run tp @s ^1.303 ^-0.02 ^-0.25 ~ ~
execute if score .this aj.frame matches 159 run tp @s ^1.362 ^-0.554 ^0.039 ~ ~