#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.936 ^0.241 ^-0.392 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.751 ^0.241 ^-0.572 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.524 ^0.241 ^-0.608 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.544 ^0.235 ^-0.613 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.561 ^0.219 ^-0.623 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.57 ^0.195 ^-0.636 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.567 ^0.165 ^-0.651 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.552 ^0.134 ^-0.663 ~ ~