#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^-0.422 ^-0.722 ^1.156 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^-0.42 ^-0.789 ^1.12 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^-0.382 ^-0.843 ^1.136 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^-0.318 ^-0.868 ^1.198 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^-0.382 ^-0.843 ^1.136 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^-0.42 ^-0.789 ^1.12 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^-0.422 ^-0.722 ^1.156 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^-0.385 ^-0.663 ^1.23 ~ ~