#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run data modify entity @s Pose.Head set value [-5.2897f,-70.2352f,20.2739f]
execute if score .this aj.frame matches 89 run data modify entity @s Pose.Head set value [-19.0652f,-70.97f,33.563f]
execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [-31.8949f,-73.4474f,46.0751f]
execute if score .this aj.frame matches 91 run data modify entity @s Pose.Head set value [-19.0652f,-70.97f,33.563f]
execute if score .this aj.frame matches 92 run data modify entity @s Pose.Head set value [-5.2897f,-70.2352f,20.2739f]
execute if score .this aj.frame matches 93 run data modify entity @s Pose.Head set value [8.3891f,-71.3352f,7.0616f]
execute if score .this aj.frame matches 94 run data modify entity @s Pose.Head set value [20.8561f,-74.1311f,-5.1395f]
execute if score .this aj.frame matches 95 run data modify entity @s Pose.Head set value [29.8489f,-78.2386f,-14.1671f]