#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^0.149 ^-0.316 ^-0.455 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^0.188 ^-0.369 ^-0.475 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^0.188 ^-0.435 ^-0.468 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^0.148 ^-0.487 ^-0.437 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^0.086 ^-0.504 ^-0.393 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^0.148 ^-0.487 ^-0.437 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^0.188 ^-0.435 ^-0.468 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^0.188 ^-0.369 ^-0.475 ~ ~