#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^0.188 ^-0.435 ^-0.468 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^0.188 ^-0.369 ^-0.475 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^0.149 ^-0.316 ^-0.455 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^0.086 ^-0.299 ^-0.416 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^0.149 ^-0.316 ^-0.455 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^0.188 ^-0.369 ^-0.475 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^0.188 ^-0.435 ^-0.468 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^0.148 ^-0.487 ^-0.437 ~ ~