#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^-0.422 ^-0.722 ^1.156 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^-0.385 ^-0.663 ^1.23 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^-0.318 ^-0.636 ^1.313 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^-0.385 ^-0.663 ^1.23 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^-0.422 ^-0.722 ^1.156 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^-0.42 ^-0.789 ^1.12 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^-0.382 ^-0.843 ^1.136 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^-0.318 ^-0.868 ^1.198 ~ ~