#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.765 ^-0.731 ^-0.19 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.818 ^-0.442 ^-0.148 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.864 ^-0.141 ^-0.147 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.893 ^0.161 ^-0.184 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.894 ^0.452 ^-0.252 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.861 ^0.723 ^-0.337 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.881 ^0.27 ^-0.111 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.765 ^-0.211 ^-0.059 ~ ~