#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.765 ^-0.47 ^-0.104 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.765 ^-0.727 ^-0.148 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.765 ^-0.981 ^-0.19 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.777 ^-0.948 ^-0.162 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.788 ^-0.911 ^-0.137 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.798 ^-0.872 ^-0.116 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.806 ^-0.831 ^-0.098 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.812 ^-0.788 ^-0.086 ~ ~