#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.149 ^-0.316 ^-0.455 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.086 ^-0.299 ^-0.416 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.149 ^-0.316 ^-0.455 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.188 ^-0.369 ^-0.475 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.188 ^-0.435 ^-0.468 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.148 ^-0.487 ^-0.437 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.086 ^-0.504 ^-0.393 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.148 ^-0.487 ^-0.437 ~ ~