#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.318 ^-0.636 ^1.313 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.385 ^-0.663 ^1.23 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.422 ^-0.722 ^1.156 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.42 ^-0.789 ^1.12 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.382 ^-0.843 ^1.136 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.318 ^-0.868 ^1.198 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.382 ^-0.843 ^1.136 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.42 ^-0.789 ^1.12 ~ ~