#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-37.5f,55f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-37.5f,55f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-19.811f,24.58f,16.0306f]