#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [20.8561f,-74.1311f,-5.1395f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [8.3891f,-71.3352f,7.0616f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-5.2897f,-70.2352f,20.2739f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-19.0652f,-70.97f,33.563f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-31.8949f,-73.4474f,46.0751f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-19.0652f,-70.97f,33.563f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-5.2897f,-70.2352f,20.2739f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [8.3891f,-71.3352f,7.0616f]