#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^0.086 ^-0.504 ^-0.393 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^0.148 ^-0.487 ^-0.437 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^0.188 ^-0.435 ^-0.468 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^0.188 ^-0.369 ^-0.475 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^0.149 ^-0.316 ^-0.455 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^0.086 ^-0.299 ^-0.416 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^0.149 ^-0.316 ^-0.455 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^0.188 ^-0.369 ^-0.475 ~ ~