#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.422 ^-0.722 ^1.156 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.42 ^-0.789 ^1.12 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.382 ^-0.843 ^1.136 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.318 ^-0.868 ^1.198 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.382 ^-0.843 ^1.136 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.42 ^-0.789 ^1.12 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.422 ^-0.722 ^1.156 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.385 ^-0.663 ^1.23 ~ ~