#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [23.3657f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [17.2943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [11.2229f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [5.1515f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-0.92f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-6.9914f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-13.0628f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-19.1343f,-22.4774f,1.0351f]