#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.877 ^-0.423 ^-0.419 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.877 ^-0.423 ^-0.419 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.877 ^-0.423 ^-0.419 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.877 ^-0.423 ^-0.419 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.877 ^-0.423 ^-0.419 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.877 ^-0.423 ^-0.419 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.877 ^-0.423 ^-0.419 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.986 ^-0.497 ^-0.014 ~ ~