#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [59.7943f,-22.4774f,1.0351f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [41.2587f,-29.8527f,3.0484f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [22.0154f,-37.0252f,6.3557f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [1.6616f,-43.8413f,11.3037f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-20.3472f,-50.0757f,18.3973f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-44.6663f,-55.39f,28.266f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [5.2736f,-39.508f,12.9286f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [48.4697f,-21.8931f,5.3233f]