#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [-5.2897f,-70.2352f,20.2739f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [8.3891f,-71.3352f,7.0616f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [20.8561f,-74.1311f,-5.1395f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [29.8489f,-78.2386f,-14.1671f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [20.8561f,-74.1311f,-5.1395f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [8.3891f,-71.3352f,7.0616f]
execute if score .this aj.frame matches 118 run data modify entity @s Pose.Head set value [-5.2897f,-70.2352f,20.2739f]
execute if score .this aj.frame matches 119 run data modify entity @s Pose.Head set value [-19.0652f,-70.97f,33.563f]