#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.717 ^-0.757 ^-0.061 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.799 ^-0.434 ^-0.024 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.846 ^-0.091 ^-0.002 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.855 ^0.26 ^0.004 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.823 ^0.606 ^-0.004 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.755 ^0.935 ^-0.022 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.855 ^0.358 ^0.045 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.717 ^-0.213 ^0.073 ~ ~