#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run data modify entity @s Pose.Head set value [138.9458f,-71.275f,-165.1056f]
execute if score .this aj.frame matches 97 run data modify entity @s Pose.Head set value [149.9508f,-74.603f,-175.3451f]
execute if score .this aj.frame matches 98 run data modify entity @s Pose.Head set value [167.2345f,-74.315f,168.2824f]
execute if score .this aj.frame matches 99 run data modify entity @s Pose.Head set value [176.6833f,-70.6557f,159.5536f]
execute if score .this aj.frame matches 100 run data modify entity @s Pose.Head set value [176.2265f,-66.0354f,160.2668f]
execute if score .this aj.frame matches 101 run data modify entity @s Pose.Head set value [176.6833f,-70.6557f,159.5536f]
execute if score .this aj.frame matches 102 run data modify entity @s Pose.Head set value [167.2345f,-74.315f,168.2824f]
execute if score .this aj.frame matches 103 run data modify entity @s Pose.Head set value [149.9508f,-74.603f,-175.3451f]