#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-14.8863f,-9.006f,21.3223f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-12.9612f,-43.3604f,24.0513f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-6.6856f,-77.7258f,21.6185f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-6.0692f,-76.4834f,21.0176f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-8.1164f,-75.2481f,23.01f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-12.1606f,-74.2145f,26.9329f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-17.68f,-73.5159f,32.2777f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-24.3261f,-73.2415f,38.7172f]