#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function temple_boss:animations/animation.model.attack_4/tree/bone2_display_0-63
execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [0f,0f,0f]