#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-47.5f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-26.7187f,0f,18.5938f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [0f,0f,30f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [5.9375f,0f,18.5937f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-26.7188f,0f,-17.3438f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-47.5f,0f,-27.5f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-23.75f,0f,-17.3437f]