#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.007 ^-0.083 ^0.357 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.072 ^0.152 ^0.485 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0 ^0.36 ^0.492 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.059 ^0.127 ^0.478 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0 ^-0.063 ^0.375 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.059 ^0.127 ^0.478 ~ ~