#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [0f,0f,18.5937f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [0f,0f,30f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [0f,0f,18.5938f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [0f,0f,-17.3437f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [0f,0f,-27.5f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [0f,0f,-15.4688f]