#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-26.7188f,0f,16.875f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-47.5f,0f,30f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-23.75f,0f,18.5938f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-23.75f,0f,-17.3437f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-47.5f,0f,-27.5f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-26.7188f,0f,-17.3438f]