#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^0.281 ^-0.047 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.11 ^0.263 ^-0.047 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.172 ^0.235 ^-0.047 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.11 ^0.263 ^-0.047 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^0.281 ^-0.047 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.102 ^0.265 ^-0.047 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.159 ^0.242 ^-0.047 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.102 ^0.265 ^-0.047 ~ ~