#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [2.9688f,0f,18.5938f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [0f,0f,30f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [-26.7188f,0f,18.5937f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [-47.5f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [-23.75f,0f,-17.3437f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [0f,0f,-27.5f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [-23.75f,0f,-17.3438f]