#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.219 ^-1.063 ^-0.344 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.112 ^-1.081 ^-0.344 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.311 ^-1.038 ^-0.344 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.112 ^-1.081 ^-0.344 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.219 ^-1.063 ^-0.344 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.507 ^-0.952 ^-0.344 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.656 ^-0.849 ^-0.344 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.478 ^-0.968 ^-0.344 ~ ~