#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-46.9731f,73.7798f,-107.1995f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-37.7169f,49.7629f,-92.8659f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-19.1908f,24.1343f,-88.8707f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-0.3034f,45.119f,-112.6547f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [27.1868f,60.8863f,-132.4078f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [87.324f,14.0766f,-107.5256f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [123.7912f,-30.4981f,-81.8313f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [60.0744f,-11.9963f,-99.7945f]