#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.219 ^-1.063 ^-0.344 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.112 ^-1.081 ^-0.344 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.311 ^-1.038 ^-0.344 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.112 ^-1.081 ^-0.344 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.219 ^-1.063 ^-0.344 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.507 ^-0.952 ^-0.344 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.656 ^-0.849 ^-0.344 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.507 ^-0.952 ^-0.344 ~ ~