#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.242 ^-0.52 ^-0.353 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.147 ^-0.559 ^-0.353 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.242 ^-0.52 ^-0.353 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.464 ^-0.291 ^-0.353 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.497 ^-0.206 ^-0.353 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.464 ^-0.291 ^-0.353 ~ ~