#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.256 ^-0.513 ^-0.353 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.147 ^-0.559 ^-0.353 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.242 ^-0.52 ^-0.353 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.464 ^-0.291 ^-0.353 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.497 ^-0.206 ^-0.353 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.464 ^-0.291 ^-0.353 ~ ~