#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.242 ^-0.52 ^-0.353 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.147 ^-0.559 ^-0.353 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.242 ^-0.52 ^-0.353 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.464 ^-0.291 ^-0.353 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.497 ^-0.206 ^-0.353 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.456 ^-0.306 ^-0.353 ~ ~