#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.242 ^-0.52 ^-0.353 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.147 ^-0.559 ^-0.353 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.242 ^-0.52 ^-0.353 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.464 ^-0.291 ^-0.353 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.497 ^-0.206 ^-0.353 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.464 ^-0.291 ^-0.353 ~ ~