#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-22.6496f,-13.9032f,-30.525f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-19.6832f,-15.3699f,-29.4828f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-22.6496f,-13.9032f,-30.525f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-16.1064f,-12.0174f,-35.7935f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [24.8984f,-11.8079f,-51.6567f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [56.3936f,-12.0174f,-63.2935f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [24.8984f,-11.8079f,-51.6567f]