#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function temple_boss:animations/animation.model.attack_4/tree/left_arm_display_0-7
execute if score .this aj.frame matches 8..15 run function temple_boss:animations/animation.model.attack_4/tree/left_arm_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-125.8974f,-2.711f,-155.3586f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-125.8974f,-2.711f,-155.3586f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-125.8974f,-2.711f,-155.3586f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-125.8974f,-2.711f,-155.3586f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-125.8974f,-2.711f,-155.3586f]