#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.412 ^-1.315 ^-0.275 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.777 ^-1.122 ^-0.445 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.935 ^-0.921 ^-0.532 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.777 ^-1.122 ^-0.445 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.412 ^-1.315 ^-0.275 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.049 ^-1.254 ^-0.104 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.187 ^-1.131 ^-0.039 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.096 ^-1.261 ^-0.116 ~ ~