#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.412 ^-1.276 ^-0.193 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.062 ^-1.288 ^-0.163 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.135 ^-1.256 ^-0.178 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.062 ^-1.288 ^-0.163 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.412 ^-1.276 ^-0.193 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.747 ^-1.161 ^-0.414 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.843 ^-0.996 ^-0.565 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.747 ^-1.161 ^-0.414 ~ ~