#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function temple_boss:animations/animation.model.attack_4/tree/lower_right_leg_root_0-63
execute if score .this aj.frame matches 64 run tp @s ^-0.412 ^-1.315 ^-0.275 ~ ~