#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [0f,0f,-2.5f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [45.8882f,-5.9851f,7.3798f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [74.7934f,-8.1988f,10.6798f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [45.8882f,-5.9851f,7.3798f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [0f,0f,-2.5f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-33.5062f,-5.0599f,-4.6177f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-49.8447f,-12.607f,-3.0969f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-28.922f,-5.5872f,-1.7513f]