#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-33.4154f,0.0661f,1.6959f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-52.2547f,-2.7152f,3.4502f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-33.4154f,0.0661f,1.6959f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [52.3771f,-24.71f,-17.4504f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [91.0045f,-40.1597f,-40.0165f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [52.3771f,-24.71f,-17.4504f]