#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-33.4154f,0.0661f,1.6959f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-52.2547f,-2.7152f,3.4502f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-33.4154f,0.0661f,1.6959f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [52.3771f,-24.71f,-17.4504f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [91.0045f,-40.1597f,-40.0165f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [48.9232f,-24.7601f,-16.9646f]