#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.412 ^-1.315 ^-0.275 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.777 ^-1.122 ^-0.445 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.935 ^-0.921 ^-0.532 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.777 ^-1.122 ^-0.445 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.412 ^-1.315 ^-0.275 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.049 ^-1.254 ^-0.104 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.187 ^-1.131 ^-0.039 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.049 ^-1.254 ^-0.104 ~ ~