#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-33.4154f,0.0661f,1.6959f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-52.2547f,-2.7152f,3.4502f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-33.4154f,0.0661f,1.6959f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [2.4932f,-1.8186f,-2.2011f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [52.3771f,-24.71f,-17.4504f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [91.0045f,-40.1597f,-40.0165f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [52.3771f,-24.71f,-17.4504f]