#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.469 ^-0.281 ^-0.353 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.503 ^-0.184 ^-0.353 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.469 ^-0.281 ^-0.353 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.252 ^-0.515 ^-0.353 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.168 ^-0.552 ^-0.353 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.252 ^-0.515 ^-0.353 ~ ~