#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,37.5f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [26.7188f,0f,54.375f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [47.5f,0f,67.5f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [30.3048f,-0.0684f,54.0674f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0f,0f,37.5f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-35.2435f,0.6154f,38.3935f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-57.3773f,1.0941f,42.4219f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-35.2435f,0.6154f,38.3935f]