#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.469 ^-0.281 ^-0.353 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.503 ^-0.184 ^-0.353 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.469 ^-0.281 ^-0.353 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.252 ^-0.515 ^-0.353 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.168 ^-0.552 ^-0.353 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.266 ^-0.506 ^-0.353 ~ ~