#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.469 ^-0.281 ^-0.353 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.503 ^-0.184 ^-0.353 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.469 ^-0.281 ^-0.353 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.252 ^-0.515 ^-0.353 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.168 ^-0.552 ^-0.353 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.252 ^-0.515 ^-0.353 ~ ~