#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.469 ^-0.281 ^-0.353 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.503 ^-0.184 ^-0.353 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.469 ^-0.281 ^-0.353 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.375 ^-0.419 ^-0.353 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.252 ^-0.515 ^-0.353 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.168 ^-0.552 ^-0.353 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.252 ^-0.515 ^-0.353 ~ ~