#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..64 run function temple_boss:animations/animation.model.attack_4/tree/right_leg_display_0-64