#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [0f,0f,37.5f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [30.3048f,-0.0684f,54.0674f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [47.5f,0f,67.5f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [30.3048f,-0.0684f,54.0674f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [0f,0f,37.5f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [-35.2435f,0.6154f,38.3935f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [-57.3773f,1.0941f,42.4219f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [-35.2435f,0.6154f,38.3935f]