#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [0f,0f,37.5f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [30.3048f,-0.0684f,54.0674f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [47.5f,0f,67.5f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [30.3048f,-0.0684f,54.0674f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [0f,0f,37.5f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-35.2435f,0.6154f,38.3935f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-57.3773f,1.0941f,42.4219f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-35.2435f,0.6154f,38.3935f]