#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^1.308 ^-0.87 ^0.895 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^1.255 ^-0.035 ^0.335 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.787 ^-0.905 ^-0.131 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.674 ^0.319 ^0.203 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.008 ^0.177 ^0.978 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.307 ^-0.975 ^0.912 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.399 ^-1.369 ^0.225 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.66 ^-0.924 ^0.496 ~ ~