#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function temple_boss:animations/animation.model.attack_4/tree/spear_display_0-63
execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [156.7229f,-25.2976f,-101.9852f]