#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.549 ^-0.069 ^0.878 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.574 ^-1.098 ^1.157 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.729 ^-1.416 ^0.895 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^1.227 ^0.017 ^0.419 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^1.103 ^-0.399 ^-0.131 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^1.193 ^-0.223 ^-0.23 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^1.196 ^0.01 ^-0.219 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^1.168 ^-0.145 ^-0.164 ~ ~