#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [108.6888f,8.0667f,-4.4214f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [150.2293f,11.974f,-122.352f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [156.7229f,-25.2976f,-71.9852f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [140.632f,-61.8806f,-115.6767f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [83.3693f,-2.1386f,-70.9316f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [50.5371f,61.2135f,-101.946f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-26.4922f,52.0472f,-168.659f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [18.3948f,-10.4031f,-142.5973f]