#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-26.4922f,52.0472f,-141.159f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [18.3948f,-10.4031f,-106.6598f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [93.7685f,-16.7483f,-138.9211f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [114.9725f,56.5655f,-46.8782f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [108.6888f,8.0667f,-4.4214f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [150.2293f,11.974f,-158.2895f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [156.7229f,-25.2976f,-129.4852f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [140.632f,-61.8806f,-151.6142f]