#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^1.308 ^-0.87 ^0.895 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^1.255 ^-0.035 ^0.335 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.787 ^-0.905 ^-0.131 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.674 ^0.319 ^0.203 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.008 ^0.177 ^0.978 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.307 ^-0.975 ^0.912 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.399 ^-1.369 ^0.225 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.66 ^-0.924 ^0.496 ~ ~