#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.957 ^-1.037 ^0.225 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-1.04 ^-0.373 ^0.496 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.478 ^0.207 ^0.878 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.574 ^-1.098 ^1.157 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^1.308 ^-0.87 ^0.895 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^1 ^0.696 ^0.335 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^1.133 ^0.148 ^-0.131 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.322 ^0.642 ^0.203 ~ ~