#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function temple_boss:animations/animation.model.attack_4/tree/spear_root_0-7
execute if score .this aj.frame matches 8..15 run function temple_boss:animations/animation.model.attack_4/tree/spear_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.201 ^0.284 ^-0.572 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.228 ^0.298 ^-0.564 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.255 ^0.312 ^-0.556 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.282 ^0.325 ^-0.547 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.308 ^0.339 ^-0.539 ~ ~