#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.008 ^0.177 ^0.978 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.784 ^-0.621 ^0.912 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-1.316 ^-0.428 ^0.225 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-1.04 ^-0.373 ^0.496 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.549 ^-0.069 ^0.878 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^1.072 ^-0.564 ^1.157 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^1.532 ^-0.175 ^0.895 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^1 ^0.696 ^0.335 ~ ~