#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-24.2268f,36.2135f,-1.2408f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-5.8088f,-39.7662f,61.5513f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-36.3038f,-38.4051f,122.2563f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-9.7684f,-46.718f,-3.7248f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [9.7558f,-21.3931f,30.1006f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [7.9303f,-23.3061f,32.7445f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [8.1883f,-23.0882f,20.3078f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [9.2836f,-22.0027f,21.1457f]