#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.201 ^-0.389 ^0.142 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.278 ^-0.603 ^0.165 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.381 ^-0.696 ^0.097 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.716 ^-0.369 ^-0.183 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.744 ^-0.513 ^-0.715 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.79 ^-0.355 ^-0.761 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.834 ^-0.201 ^-0.756 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.82 ^-0.327 ^-0.732 ~ ~