#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [180f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [95.625f,40.7813f,18.5938f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [15f,72.5f,30f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [95.625f,40.7812f,18.5937f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [180f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [122.8125f,-4.5312f,-17.3438f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [45f,0f,-27.5f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [28.125f,0f,-17.3437f]