#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.201 ^-0.389 ^0.142 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.038 ^-0.645 ^0.074 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.201 ^-0.684 ^0.021 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.014 ^-0.598 ^0.099 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.201 ^-0.389 ^0.142 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.542 ^-0.337 ^0.165 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.739 ^-0.082 ^0.097 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.786 ^0.115 ^-0.263 ~ ~