#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [45f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [122.8125f,-4.5313f,16.875f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [180f,0f,30f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [95.625f,40.7813f,18.5938f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [15f,72.5f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [95.625f,40.7813f,-17.3438f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [180f,0f,-27.5f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [122.8125f,-4.5313f,-17.3438f]