#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function temple_boss:animations/animation.model.attack_4/tree/upper_left_arm_root_0-63
execute if score .this aj.frame matches 64 run tp @s ^0.744 ^-0.513 ^-0.715 ~ ~