#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.717 ^-0.386 ^-0.799 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.808 ^-0.632 ^-0.634 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-1.014 ^-0.058 ^-0.552 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.808 ^-0.632 ^-0.634 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.717 ^-0.386 ^-0.799 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.491 ^-0.964 ^-0.594 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.316 ^-1.01 ^-0.061 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.507 ^-0.845 ^0.025 ~ ~