#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function temple_boss:animations/animation.model.attack_4/tree/upper_right_arm_root_0-7
execute if score .this aj.frame matches 8..15 run function temple_boss:animations/animation.model.attack_4/tree/upper_right_arm_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.002 ^-0.757 ^0.78 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.002 ^-0.757 ^0.78 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.002 ^-0.757 ^0.78 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.002 ^-0.757 ^0.78 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.002 ^-0.757 ^0.78 ~ ~