#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.717 ^-0.757 ^-0.061 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.913 ^-0.531 ^-0.594 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.783 ^0.016 ^-0.799 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.808 ^-0.632 ^-0.634 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.881 ^-0.566 ^-0.552 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.32 ^-0.998 ^-0.634 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.487 ^-0.681 ^-0.799 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.491 ^-0.964 ^-0.594 ~ ~