#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.744 ^-0.513 ^-0.715 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.728 ^-0.379 ^-0.21 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.011 ^-0.446 ^0.142 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.038 ^-0.645 ^0.074 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.137 ^-0.701 ^0.021 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.303 ^-0.505 ^0.099 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.329 ^-0.259 ^0.142 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.542 ^-0.337 ^0.165 ~ ~