#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [45f,0f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [28.125f,0f,18.5937f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [45f,0f,30f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [122.8125f,-4.5312f,18.5938f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [180f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [95.625f,40.7812f,-17.3437f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [15f,72.5f,-27.5f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [95.625f,40.7813f,-17.3438f]