#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.temple_boss.animation.model.attack_5.loopMode matches 0 run function temple_boss:animations/animation.model.attack_5/stop
execute if score @s aj.temple_boss.animation.model.attack_5.loopMode matches 1 run function temple_boss:animations/animation.model.attack_5/pause
execute if score @s aj.temple_boss.animation.model.attack_5.loopMode matches 2 run function temple_boss:animations/animation.model.attack_5/zzz/execute/85