#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run function temple_boss:set_variant/attack
execute if score .this aj.frame matches 30 run function temple_boss:set_variant/default
execute if score .this aj.frame matches 160 run function temple_boss:animations/animation.model.attack_3/stop