#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.temple_boss.animation.model.test.loopMode matches 0 run function temple_boss:animations/animation.model.test/stop
execute if score @s aj.temple_boss.animation.model.test.loopMode matches 1 run function temple_boss:animations/animation.model.test/pause
execute if score @s aj.temple_boss.animation.model.test.loopMode matches 2 run function temple_boss:animations/animation.model.test/zzz/execute/47