#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['new','aj.temple_boss','aj.temple_boss.root']}
execute as @e[type=minecraft:marker,tag=aj.temple_boss.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function temple_boss:summon/zzz/execute/8
function temple_boss:assert_animation_flags